<div id="esquerda">

    <div style="margin: 10px">

        <a style="float: right;" class="btn btn-success btn-large" href="<?php echo $this->baseUrl(); ?>/admin/plano-de-contas/novo/?nolayout=<?php echo $this->layout?>">
            <i class="icon-plus icon-white"></i> Novo </a>


        <div class="page-header" >
            <h2>Plano de Contas</h2>
        </div>

        <form method="GET" action="" style="display: none;" id="form_filtrar">
            <div class="row well">
                <a id="btn_close" class="close" href="#">&times;</a>


                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="codigo">Codigo</label>
                        <div class="controls">
                            <input class="input-xlarge" id="codigo" name="codigo" type="text" value="<?php echo $this->repository_filter->getParamByField('codigo') ?>">
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="descricao">Descrição</label>
                        <div class="controls">
                            <input class="input-xlarge" id="descricao" name="descricao" type="text" value="<?php echo $this->repository_filter->getParamByField('descricao') ?>">
                        </div>
                    </div>
                </div>
                <div class="span8">
                    <hr/>
                    <button type="submit" data-loading-text="Filtrando..." class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtrar</button>
                </div>

            </div>
        </form>

        <?php echo $this->flashMessenger(); ?>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><?php echo ViewUtil::getOrderBy('Descrição', 'descricao', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Tipo', 'tipo', $this->repository_order) ?></th>                    
                    <th><?php echo ViewUtil::getOrderBy('Natureza', 'natureza_operacao', $this->repository_order) ?></th>                    
                    <th colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->list as $item): ?>

                    <tr>
                        <td><?php echo $item->codigo ?> - <?php echo $item->descricao ?></td>
                        <td><?php echo $item->getTipo() ?></td>
                        <td><?php echo $item->getNatureza() ?></td>

                        <td width="20px" style="text-align: center; vertical-align: middle;">
                            <a href="<?php echo $this->baseUrl(); ?>/admin/plano-de-contas/deletar/id/<?php echo $item->id; ?>?nolayout=<?php echo $this->layout?>"><i title="excluir" class="icon-trash"></i></a>
                        </td>
                       
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <?php if (isset($this->list)) echo $this->paginationControl($this->list, "All", "paginator.phtml", $this->list_params); ?>

    </div>

</div>