<script type="text/javascript">
    $(function() {
        $('#tipo').change(function() {
            var tipo = ""
            $("#tipo option:selected").each(function() {
                tipo = $(this).val();
            });
            if (tipo == <?php echo PlanoDeContas::FILHO ?>) {
                $('.plano_pai').show('slow');
            } else {
                $('.plano_pai').hide('slow');
            }
        })
                .trigger('change');

    });
</script>
<form id="form_plano_de_conta" method="POST" action="" enctype="multipart/form-data">
    <fieldset>
        <?php echo $this->flashMessenger(); ?>
        <div class="row well">
            <div class="span4">
                <div class="control-group">
                    <label class="control-label" for="descricao">Descrição</label>
                    <div class="controls">
                        <input class="input-xlarge" id="descricao_conta" placeholder="Descrição do Plano de Contas" name="descricao" type="text" value="<?php echo $this->plano_de_contas->descricao ?>">
                    </div>
                </div>
            </div>
            <div class="span2">
                <div class="control-group">
                    <label class="control-label" for="tipo">Tipo</label>
                    <div class="controls">
                        <select  class="input-small" name="tipo" id="tipo">          
                            <option <?php echo ViewUtil::fillFieldSelect($this->plano_de_contas->tipo, PlanoDeContas::PAI) ?> value="<?php echo PlanoDeContas::PAI ?>">Pai</option>
                            <option <?php echo ViewUtil::fillFieldSelect($this->plano_de_contas->tipo, PlanoDeContas::FILHO) ?> value="<?php echo PlanoDeContas::FILHO ?>">Filho</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="span2">
                <div class="control-group">
                    <label class="control-label" for="natureza">Natureza</label>
                    <div class="controls">
                        <select  class="input-small" name="natureza" id="natureza">          
                            <option <?php echo ViewUtil::fillFieldSelect($this->plano_de_contas->natureza_operacao, PlanoDeContas::CREDITO) ?> value="<?php echo PlanoDeContas::CREDITO ?>">Crédito</option>
                            <option <?php echo ViewUtil::fillFieldSelect($this->plano_de_contas->natureza_operacao, PlanoDeContas::DEBITO) ?> value="<?php echo PlanoDeContas::DEBITO ?>">Débito</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="span2 plano_pai" style="display: none">
                <div class="control-group">
                    <label class="control-label" for="plano_pai">Plano de Contas Pai</label>
                    <div class="controls">
                        <select  class="input-large" name="plano_pai" id="plano_pai">
                            <option value="0">[  Selecione o Plano ]</option>
                            <?php foreach ($this->planos_pais as $plano): ?>
                                <option <?php echo ViewUtil::fillFieldSelect($this->plano_de_contas->plano_de_contas_id, $plano->id) ?> value="<?php echo $plano->id ?>"><?php echo $plano->descricao ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>   
    </fieldset>
    <hr/>
    <div style="width: 100%;height: 20px">
        <div class="btn-concluir">
            <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/admin/plano-de-contas/?nolayout=<?php echo $this->layout?>">Cancelar</a>
            <button type="submit" class="btn btn-success btn-large">Salvar</button>
        </div>
    </div>
</form>
