<div id="esquerda">

    <div style="margin: 10px">



        <a style="float: right;" class="btn btn-success btn-large" href="<?php echo $this->baseUrl(); ?>/admin/fornecedor/novo/">
            <i class="icon-plus icon-white"></i> Novo </a>

        <button style="float: right; margin-right: 5px;"  type="button" id="btn_filtrar" class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtro</button>


        <div class="page-header" >
            <h2>Fornecedores</h2>
        </div>

        <form method="GET" action="" style="display: none;" id="form_filtrar">
            <div class="row well">
                <a id="btn_close" class="close" href="#">&times;</a>



                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="descricao">Descrição</label>
                        <div class="controls">
                            <input class="input-large" id="descricao_fornecedor" name="descricao" type="text" value="<?php echo $this->repository_filter->getParamByField('descricao') ?>">
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="categoria">Categoria</label>
                        <div class="controls">
                            <select data-placeholder="[  Selecione a Categoria ]" class="input-xlarge chzn-select-deselect" name="categoria" id="categoria">
                                <option value="0"></option>
                                <?php foreach ($this->fornecedores_categorias as $categoria): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('categoria'), $categoria->id) ?> value="<?php echo $categoria->id ?>"><?php echo $categoria->descricao ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span2">
                    <div class="control-group">
                        <label class="control-label" for="status">Status</label>
                        <div class="controls">
                            <select data-placeholder="[ Todos ]" class="input-small chzn-select-deselect" name="status" id="status">
                                <option value="0"></option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('status'), Fornecedor::ATIVO) ?> value="<?php echo Fornecedor::ATIVO ?>">Ativo</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('status'), Fornecedor::INATIVO) ?> value="<?php echo Fornecedor::INATIVO ?>">Inativo</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="span11">
                    <hr/>
                    <button type="submit" data-loading-text="Filtrando..." class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtrar</button>
                </div>

            </div>
        </form>

        <?php echo $this->flashMessenger(); ?>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th><?php echo ViewUtil::getOrderBy('Descrição', 'descricao', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Telefone', 'telefone', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Contato', 'contato', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Categoria', 'fornecedor_categoria_id', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Status', 'status', $this->repository_order) ?></th>                    
                    <th colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->list as $item): ?>

                    <tr>
                        <td><?php echo $item->descricao ?></td>
                        <td><?php echo AppUtil::convertIntToCelular($item->Endereco[0]->telefone_1) ?></td>
                        <td><?php echo $item->contato ?></td>
                        <td><?php echo $item->FornecedorCategoria->descricao ?></td>
                        <td><?php echo $item->getStatus() ?></td>
                        <td width="20px" style="text-align: center; vertical-align: middle;">
                            <a href="<?php echo $this->baseUrl(); ?>/admin/fornecedor/editar/id/<?php echo $item->id; ?>"><i title="editar" class="icon-pencil"></i></a>
                        </td>
                        <td width="20px" style="text-align: center; vertical-align: middle;">
                            <a onclick="return confirm('Confirma a exclusão deste fornecedor ?')" href="<?php echo $this->baseUrl(); ?>/admin/fornecedor/deletar/id/<?php echo $item->id; ?>"><i title="excluir" class="icon-trash"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <?php if (isset($this->list)) echo $this->paginationControl($this->list, "All", "paginator.phtml", $this->list_params); ?>

    </div>

</div>