<form id="form_compra" method="POST" action="" enctype="multipart/form-data">
    <fieldset>
        <?php echo $this->flashMessenger(); ?>
            <div class="row well">
                <div class="span9 fornecedor">
                    <div class="control-group">
                        <label class="control-label" for="cliente">Cliente</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Cliente ]" class="input-xxlarge chzn-select-deselect" name="cliente" id="cliente">
                                <option value="0"></option>
                                <?php foreach ($this->clientes as $cliente): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->produto->cliente_id, $cliente->id) ?> value="<?php echo $cliente->id ?>"><?php echo $cliente->nome ." ".$cliente->sobrenome ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span2">
                    <div class="control-group">
                        <label class="control-label" for="data_compra">Data Compra</label>
                        <div class="controls">
                            <div class="input-append">
                                <input class="input-small txData" id="data_compra" placeholder="__/__/____"name="data_compra" type="text"  value="<?php echo AppUtil::convertDateToString($this->produto->data_movimento) ?>">
                                <span class="add-on"><span class="icon-calendar"></span></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="tipo">Tipo</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Tipo ]" class="input-large" name="tipo" id="tipo">
                                <option <?php echo ViewUtil::fillFieldSelect($this->produto->tipo, Movimento::VENDA) ?> value="<?php echo Movimento::VENDA ?>">VENDA</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="span6" >
                    <div class="control-group">
                        <label class="control-label" for="forma_pagamento">Forma de Pagamento</label>
                        <div class="controls">
                            <select  class="input-xlarge" name="forma_pagamento" id="forma_pagamento">
                                <option value="0">[ Selecione a Forma ]</option>
                                <?php foreach ($this->forma_pagamento as $pagamento): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->produto->pagamento_tipo_id, $pagamento->id) ?> value="<?php echo $pagamento->id ?>"><?php echo $pagamento->descricao ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="status">Status</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Status ]" class="input-large" name="status" id="status">
                                <option <?php echo ViewUtil::fillFieldSelect($this->produto->status, Movimento::ABERTO) ?> value="<?php echo Movimento::ABERTO ?>">Aberto</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->produto->status, Movimento::REALIZADO) ?> value="<?php echo Movimento::REALIZADO ?>">Realizado</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->produto->status, Movimento::CANCELADO) ?> value="<?php echo Movimento::CANCELADO ?>">Cancelado</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="control-group">
                        <label class="control-label" for="valor">Valor</label>
                        <div class="controls">
                            <input class="input-small txValor" id="valor"  name="valor" maxlength="7" type="text" value="<?php echo AppUtil::convertFloatToString($this->produto->valor) ?>">
                            <span class="help-block">R$</span>
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="observacao">Observação</label>
                        <div class="controls">
                            <input class="input-xxlarge" id="observacao_compra" name="observacao" type="text" value="<?php echo $this->produto->observacao ?>">
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row well">

            </div>
    </fieldset>


    <hr/>
    <div style="width: 100%;height: 20px">
    <div class="btn-concluir">
        <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/admin/produto-venda/">Cancelar</a>
        <button type="submit" class="btn btn-success btn-large">Salvar</button>
    </div>
    </div>
</form>
