<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td height="120" align="center" style="background: url(<?php echo $this->baseUrl(); ?>/content/img/bg-pattern.png); background-color: #0C5AB2;">
                <table width="95%">
                    <tbody>
                        <tr>
                            <td align="right">
                                <a target="_blank" href="<?php echo $this->baseUrl(); ?>/institucional">
                                    <img style="height: 130px; float: left;"  src="<?php echo AppUtil::getFileView($this->escola, 'e', '100') ?>">
                                </a>
                            </td>
                            <td>
                                <div style=" text-align: right;">
                                    <a target="_blank" href="http://www.sbrasilsolucoes.com/" style="font-family: Arial; font-size: 52px;color: #fff; text-decoration:none; text-shadow: 0.03em 0.02em #000;"><b>SBrasil</b> Soluções</a>
                                    <p style="font-family: Arial; font-size: 12px; color: #fff; margin-top: 5px; text-shadow: 0.1em 0.1em #000;">Especializada em desenvolvimento de Sistemas para Web</p>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>

        <tr>
            <td bgcolor="#dddcd9" align="center">
                <table width="95%" cellpadding="30">
                    <tbody><tr>
                            <td align="left">
                                <font face="Arial" style="font-size:14px" >
                                Olá <?php echo $this->aluno->ResponsavelAluno[0]->getFirstName() ?>,
                                <br><br>
                                Este email é lembrando qua a mensalidade escolar do(a) aluno(a) <?php echo $this->aluno->nome ?>, já está disponível para que seja realizado o pagamento.
                                <br><br>
                                Lembre-se de pagar em dia à fim de evitar multa e juros.
                                <br><br>
                                O <?php echo $this->escola->nome_fantasia ?>, sente-se honrado de tê-lo(a) conosco. 
                                <br><br>
                                Obs: Caso necessário você ainda tem acesso ao histórico financeiro das mensalidades escolares, para isso basta acessar o nosso Portal.
                                <br><br>
                                Para acessar o sistema basta ir o link <a target="_blank" href="siges.sbrasilsolucoes.com/aluno">siges.sbrasilsolucoes.com/aluno</a>
                                <br><br>
                                <b>Equipe <a target="_blank" href="<?php echo $this->escola->EscolaConfiguracao[0]->site?>"><?php echo $this->escola->nome_fantasia ?></a></b>
                                <br>
                                </font>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>

        <tr>
            <td align="center">  
                <br>
                <?php $ano = date('Y') ?>
                <p style="font-family:'Arial';font-size:11px;color:#888">©&nbsp;<?php echo $ano ?>&nbsp;<a style="color:#666666" target="_blank" href="sbrasilsolucoes.com">SBrasilSoluções.com</a></p>
            </td>
        </tr>

    </tbody>
</table>