<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td height="120" align="center" style="background: #0C5AB2">
                <table width="95%">
                    <tbody>
                        <tr>
                            <td align="right">
                                <a target="_blank" href="<?php echo $this->baseUrl(); ?>/institucional">
                                    <img style=" height: 150px; float: left;" src="http://www.sbrasilsolucoes.com/content/img/logo-cegetsemani.png">
                                </a>
                            </td>
                            <td>
                                <div style=" text-align: right;">
                                    <a target="_blank" href="<?php echo $this->baseUrl(); ?>/institucional" style="font-family: Arial; font-size: 28px; color: #fff; text-decoration:none; text-shadow: 0.03em 0.02em #000;"><b>Centro Educacional Getsêmani</b></a>
                                    <p style="font-family: Arial; font-size: 14px; color: #fff; margin-top: -5px; text-shadow: 0.1em 0.1em #000;">Um princípio cristão de aprender</p>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>

        <tr>
            <td bgcolor="#f2f2f2" align="center">
                <table width="95%" cellpadding="30">
                    <tbody><tr>
                            <td align="left">
                                <font face="Arial" style="font-size:14px" >
                                <?php echo $this->mensagem ?>
                                </font>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>

        <tr>
            <td align="center">  
                <br>
                <p style="font-family:'Arial';font-size:11px;" align="center">
                    Para garantir que nossos comunicados cheguem em sua caixa de entrada,<br>
                    adicione o e-mail <a href="mailto:<?php echo $this->remetente ?>" style="color:#666666" target="_blank"><?php echo $this->remetente ?></a> ao seu catálogo de endereços.
                </p>
                <?php $ano = date('Y') ?>
                <p style="font-family:'Arial';font-size:11px;color:#888">©&nbsp;<?php echo $ano ?>&nbsp;<a style="color:#666666" target="_blank" href="<?php echo $this->baseUrl(); ?>/">Centro Educacional Getsêmani</a></p>
            </td>
        </tr>

    </tbody>
</table>