<h1>An error occurred</h1>
<h2><?php echo $this->message ?></h2>

<h3>Exception information:</h3>
<p>
    <b>Data:</b> <?php echo $this->data ?><br/>
    <b>Escola:</b> <?php echo $this->escola ?><br/>
    <b>Usuário:</b> <?php echo $this->usuario ?><br/>
    <b>URL:</b> <?php echo $this->url ?>
</p>

<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?></pre>