<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td height="120" align="center" style="background: url(<?php echo $this->baseUrl(); ?>/content/img/bg-pattern.png); background-color: #0C5AB2;">
                <table width="95%">
                    <tbody>
                        <tr>
                            <td align="right">
                                <a target="_blank" href="<?php echo $this->baseUrl(); ?>">
                                    <img style=" height: 150px; float: left;" src="http://www.sbrasilsolucoes.com/content/img/logo-ela.png">
                                </a>
                            </td>
                            <td>
                                <div style=" text-align: right;">
                                    <a target="_blank" href="<?php echo $this->baseUrl(); ?>" style="font-family: Arial; font-size: 52px;color: #fff; text-decoration:none; text-shadow: 0.03em 0.02em #000;"><b>Holy</b> Solutions</a>
                                    <p style="font-family: Arial; font-size: 12px; color: #fff; margin-top: 5px; text-shadow: 0.1em 0.1em #000;">Especializada em desenvolvimento de Sites e Sistemas para Web</p>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>

        <tr>
            <td bgcolor="#dddcd9" align="center">
                <table width="95%" cellpadding="30">
                    <tbody><tr>
                            <td align="left">
                                <font face="Arial" style="font-size:14px" >
                                Olá <?php echo $this->usuario->nome ." ".$this->usuario->sobrenome ?>, estamos lembrando sua senha conforme solicitado para que você possa ter total acesso a sua conta em seu sistema.
                                <br><br>
                                Email: <?php echo $this->usuario->email ?>
                                <br>
                                Senha: <?php echo $this->usuario->senha ?>
                                <br><br>
                                <br><br>
                                Qualquer dúvida entre em contato conosco, que teremos o prazer em lhe atender.
                                <br>
                                Email : <a href="mailto:samuelteclado@hotmail..com">samuelteclado@hotmail.com</a>
                                <br><br><br>
                                Equipe <?php echo $this->empresa->nome_fantasia?>
                                <br>
                                </font>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>

        <tr>
            <td align="center">  
                <br>
                <p style="font-family:'Arial';font-size:11px;" align="center">
                    <a href="http://www.sbrasilsolucoes.com/" style="color:#666666" target="_blank">Holy Solutions</a> respeita a sua privacidade e é contra o spam na rede.<br></p>
                <?php $ano = date('Y') ?>
                <p style="font-family:'Arial';font-size:11px;color:#888">©&nbsp;<?php echo $ano ?>&nbsp;<a style="color:#666666" target="_blank" href="http://www.sbrasilsolucoes.com/">Holy Solutions</a></p>
            </td>
        </tr>

    </tbody>
</table>