<table width="100%" align="center" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td height="120" align="center" style="background: url(<?php echo $this->baseUrl(); ?>/content/img/bg-pattern.png); background-color: #ff5ea5;">
                <table width="95%">
                    <tbody>
                        <tr>
                            <td align="right">
                                <a target="_blank" href="<?php echo $this->baseUrl(); ?>/institucional">
                                    <img style="height: 130px; float: left;"  src="https://www.espacoela.com/content/img/logo-ela-branco.png">
                                </a>
                            </td>
                            <td>
                                <div style=" text-align: right;">
                                    <a target="_blank" href="" style="font-family: Arial; font-size: 52px;color: #fff; text-decoration:none; text-shadow: 0.03em 0.02em #000;"><b>Holy</b> Solutions</a>
                                    <p style="font-family: Arial; font-size: 12px; color: #fff; margin-top: 5px; text-shadow: 0.1em 0.1em #000;">Especializada em desenvolvimento de Sistemas Web</p>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>

        <tr>
            <td bgcolor="#dddcd9" align="center">
                <table width="95%" cellpadding="30">
                    <tbody><tr>
                            <td align="left">
                                <font face="Arial" style="font-size:14px" >
                                Olá <?php echo $this->usuario->nome ." ". $this->usuario->sobrenome?>
                                <br><br>
                                Seja Bem-vindo(a) ao <?php echo $this->empresa->nome_fantasia?>
                                <br><br>
                                Que possamos somar conhecimentos, experiencias e talentos. Seja bem vindo(a) à nossa equipe!
                                <br><br>
                                O <?php echo $this->empresa->nome_fantasia ?>, sente-se honrado de tê-lo(a) conosco.
                                <br><br>
                                <br><br>
                                Seu usuario de acesso ao sistema é: <?php echo $this->usuario->email?>
                                <br>
                                Senha: <?php echo $this->usuario->senha?>
                                <br><br>
                                Assim que você acessar o sistema poderá efetuar a troca da senha. 
                                <br><br>
                                Para acessar o sistema basta ir o link <a target="_blank" href="https://www.espacoela.com/admin">espacoela.com/admin</a>
                                <br><br>
                                <b>Equipe <?php echo $this->empresa->nome_fantasia ?></a></b>
                                <br>
                                </font>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>

        <tr>
            <td align="center">  
                <br>
                <p style="font-family:'Arial';font-size:11px;color:#888">©&nbsp;<?php echo date('Y') ?>&nbsp;<a style="color:#666666" target="_blank" href="#">HolySolutions</a></p>
            </td>
        </tr>

    </tbody>
</table>