<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="pt-br">
<style>
    .text-input{
        border:1px solid #ccc;
        -webkit-box-shadow:inset 0 1px 0 #eee,#fff 0 1px 0;
        -moz-box-shadow:inset 0 1px 0 #eee,#fff 0 1px 0;
        box-shadow:inset 0 1px 0 #eee,#fff 0 1px 0;
        padding: 4px; margin: 2px;
        color: #057ED0;
    }
    .text-input:focus{
        background-color:#f8fdf8;
        background-image:url(content/img/FunTxtAti.jpg)
    }

    input, textarea {
        -webkit-box-shadow: inset 0 1px 3px rgba(0,0,0,.05),0 1px 0 rgba(255,255,255,.075);
        -moz-box-shadow: inset 0 1px 3px rgba(0,0,0,.05),0 1px 0 rgba(255,255,255,.075);
        box-shadow: inset 0 1px 3px rgba(0,0,0,.05),0 1px 0 rgba(255,255,255,.075);
        -webkit-transition: .2s linear background;
        -moz-transition: .2s linear background;
        transition: .2s linear background;
    }
    input, textarea, select {
        display: inline-block;
        padding: 4px;
        margin: 0;
        outline: none;
        background-color: white;
        border: 1px solid #CCC;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
    }
    label, input, textarea, select, button {
        font: 13px/20px "HelveticaNeue","Helvetica Neue",Helvetica,Arial,sans-serif;
    }

    .front-signin .submit {
        height: 30px;
        -webkit-box-shadow: 0 1px 0 #fff;
        -moz-box-shadow: 0 1px 0 #fff;
        box-shadow: 0 1px 0 #fff;
    }

    .btn {
        background-color: #DDD;
        background-repeat: repeat-x;
        background-image: -khtml-gradient(linear,left top,left bottom,from(white),to(#DDD));
        background-image: -moz-linear-gradient(white,#DDD);
        background-image: -ms-linear-gradient(white,#DDD);
        background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0%,white),color-stop(100%,#DDD));
        background-image: -webkit-linear-gradient(white,#DDD);
        background-image: -o-linear-gradient(white,#DDD);
        background-image: linear-gradient(white,#DDD);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff',endColorstr='#dddddd');
    }

    .btn {
        position: relative;
        display: inline-block;
        overflow: visible;
        padding: 5px 10px;
        font-size: 13px;
        font-weight: bold;
        line-height: 18px;
        color: #333;
        text-shadow: 0 1px 0 rgba(255, 255, 255, .5);
        background-color: #CCC;
        background-repeat: no-repeat;
        border: 1px solid #CCC;
        cursor: pointer;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
        border-radius: 0 url(0);
        -webkit-box-shadow: 0 1px 0 rgba(255,255,255,.5);
        -moz-box-shadow: 0 1px 0 rgba(255,255,255,.5);
        box-shadow: 0 1px 0 rgba(255,255,255,.5);
    }


    .primary-btn, .following.first-hover .follow-btn.hover, .following .follow-btn, .following .follow-button.cancel-hover-style.hover, .following .follow-button {
        color: white;
        text-shadow: 0 -1px 0 rgba(0, 0, 0, .25);
        background-color: #019AD2;
        background-repeat: repeat-x;
        background-image: -khtml-gradient(linear,left top,left bottom,from(#33BCEF),to(#019AD2));
        background-image: -moz-linear-gradient(#33BCEF,#019AD2);
        background-image: -ms-linear-gradient(#33BCEF,#019AD2);
        background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0%,#33BCEF),color-stop(100%,#019AD2));
        background-image: -webkit-linear-gradient(#33BCEF,#019AD2);
        background-image: -o-linear-gradient(#33BCEF,#019AD2);
        background-image: linear-gradient(#33BCEF,#019AD2);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#33bcef',endColorstr='#019ad2',GradientType=0);
        border-color: #057ED0;
        -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,.1);
        -moz-box-shadow: inset 0 1px 0 rgba(255,255,255,.1);
        box-shadow: inset 0 1px 0 rgba(255,255,255,.1);
    }

    .btn:hover, .photo-selector:not(.disabled):hover .btn, .follow-combo.open .btn-user-actions, .user-dropdown.open {
        color: white;
        text-decoration: none;
        background-color: #33BCEF;
        background-image: -khtml-gradient(linear,left top,left bottom,from(#33BCEF),to(#12A7DE));
        background-image: -moz-linear-gradient(#33BCEF,#12A7DE);
        background-image: -ms-linear-gradient(#33BCEF,#12A7DE);
        background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0%,#33BCEF),color-stop(100%,#12A7DE));
        background-image: -webkit-linear-gradient(#33BCEF,#12A7DE);
        background-image: -o-linear-gradient(#33BCEF,#12A7DE);
        background-image: linear-gradient(#33BCEF,#12A7DE);
        filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
        border-color: #057ED0;
    }

    .front-signin, .front-signup {
        background: white;
        background: -webkit-gradient(linear,left top,left bottom,color-stop(0%,white),color-stop(100%,#DDD));
        background: -webkit-linear-gradient(top,white 0,#DDD 100%);
        background: -moz-linear-gradient(top,white 0,#DDD 100%);
        background: -ms-linear-gradient(top,white 0,#DDD 100%);
        background: -o-linear-gradient(top,white 0,#DDD 100%);
        background: linear-gradient(top,white 0,#DDD 100%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff',endColorstr='#dddddd',GradientType=0);
        border-left: solid 1px #EEE;
        border-right: solid 1px #EEE;
        border-bottom: solid 1px #CCC;
        -webkit-box-shadow: 0 1px 0 rgba(0,0,0,.1);
        -moz-box-shadow: 0 1px 0 rgba(0,0,0,.1);
        box-shadow: 0 1px 0 rgba(0,0,0,.1);
    }
    .body-content{
        border-radius: 10px;
        padding: 10px;
        margin: auto;
        width: 600px;
        border: 1px solid #ddd;
    }

    .content {
        background: none repeat scroll 0 0 #f2f2f2;
        border: 1px solid #ddd;
        padding: 10px;
    }

    h4{
        font-size: 18px;
        margin: 20px 0px;
    }


</style>
<head>
    <title><?php echo PageUtil::getTitle() ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="author" content="SBrasil Soluções" />
    <meta name="robots" content="noindex, nofollow" />
    <meta name="language" content="pt-br" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/content/css/layout_novo/site.css') ?>
    <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/content/img/favicon.ico" type="image/ico" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/content/css/jquery-ui-1.8.16.custom.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/content/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/content/css/jquery.multiselect.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/content/css/jquery.multiselect.filter.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/content/js/jquery-fileupload/jquery.fileupload-ui.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/content/colorbox/example1/colorbox.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/content/chosen/chosen.css" />

    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/content/ddsmoothmenu/ddsmoothmenu.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/content/ddsmoothmenu/ddsmoothmenu-v.css" />

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/bootstrap/js/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/bootstrap/js/application.js"></script>

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/js/jquery-1.6.2.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/js/jquery-ui-1.8.16.custom.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/js/jquery.maskedinput-1.3.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/js/jquery.maskMoney.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/js/jquery.multiselect.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/js/jquery.multiselect.filter.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/js/ckeditor/ckeditor.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/content/colorbox/colorbox/jquery.colorbox.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/content/chosen/chosen.jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/content/ddsmoothmenu/ddsmoothmenu.js"></script>

    <script type="text/javascript">
        var datapickerconfig = {
            closeText: 'Fechar',
            prevText: '&#x3c;Anterior',
            nextText: 'Pr&oacute;ximo&#x3e;',
            currentText: 'Hoje',
            monthNames: ['Janeiro', 'Fevereiro', 'Mar&ccedil;o', 'Abril', 'Maio', 'Junho',
                'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun',
                'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
            dayNames: ['Domingo', 'Segunda-feira', 'Ter&ccedil;a-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sabado'],
            dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
            dayNamesMin: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
            weekHeader: 'Sm',
            dateFormat: 'dd/mm/yy',
            firstDay: 0,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: '',
            changeMonth: true,
            changeYear: true
        };

        $(function() {


            $('.txData').datepicker(datapickerconfig);
            $(".txData").mask("99/99/9999");
            $(".txAniversario").mask("99/99");
            $(".txCep").mask("99999-999");
            $(".txTelefone").mask("(99) 9999-9999");
            $(".txCpf").mask("999.999.999-99");
            $(".txCnpj").mask("99.999.999/9999-99");
            $(".txValor").maskMoney({symbol: "", decimal: ",", thousands: "", precision: 2, allowNegative: false, allowZero: true});
            $(".txValorNegativo").maskMoney({symbol: "", decimal: ",", thousands: "", precision: 2, allowNegative: true, allowZero: true});

            $('form').submit(function() {
                $('button[type=submit]', this).attr('disabled', 'disabled');
            });



            //CKEDITOR Create a new editor inside the <textarea id="descricao">, setting its value to html
            var config = {
                resize_enabled: false,
                uiColor: '#f2f2f2',
                toolbar: [
                    {name: 'basicstyles', items: ['Bold', 'Italic']},
                    {name: 'paragraph', items: ['NumberedList', 'BulletedList']}
                ]
            };

            if ($('#descricao').length != 0) {
                CKEDITOR.replace('descricao', config);
            } else if ($('#observacao').length != 0) {
                CKEDITOR.replace('observacao', config);
            }
            //CKEDITOR

            //COLORBOX
            $(".popup_d").colorbox({rel: 'popup_d', maxWidth: "80%", maxHeight: "80%", arrowKey: false, fixed: true});
            $(".popup_b").colorbox({iframe: true, width: "750px", height: "90%", fixed: true, opacity: 0.99});
            //COLORBOX


            //FORM PESQUISAR
            $('#btn_filtrar').click(function() {
                $("#form_filtrar").toggle('slow');
                $('#btn_filtrar').hide();
            });

            $('#btn_close').click(function() {
                $("#form_filtrar").toggle('slow');
                $('#btn_filtrar').fadeIn('slow');
            });

            $(".chzn-select").chosen({
                no_results_text: "Não foram encontrados resultados para"
            });

            $(".chzn-select-deselect").chosen({
                allow_single_deselect: true,
                no_results_text: "Não foram encontrados resultados para"

            });
            //FORM PESQUISAR

        });
    </script>
    <script type="text/javascript">

        ddsmoothmenu.init({
            mainmenuid: "smoothmenu1", //menu DIV id
            orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
            classname: 'ddsmoothmenu', //class added to menu's outer DIV
            //customtheme: ["#1c5a80", "#18374a"],
            contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
        });

    </script>
    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-47767800-1', 'sbrasilsolucoes.com');
        ga('send', 'pageview');

    </script>

    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/content/css/site_print.css" media="print" />

</head>
<body>

<div id="wrap">

    <div id="content">
        <style>
            body {
                background-image: url('/content/img/bg.jpg');
                background-position: 0 0;
                background-repeat: repeat;
            }
        </style>

        <div class="noprint" style="width: auto; padding: 20px;height: 50px;background: #f9e8f9 url(/content/img/fundo.jpg);border: 1px solid #ddd;margin: 0px auto 5px auto; ">
            <?php include_once APPLICATION_PATH . '/include/menu_drop/perfil.php'; ?>
        </div>
        <?php if (Zend_Auth::getInstance()->getIdentity()->id != null) : ?>
            <div class="noprint" id="top" style="height: 41px; margin-top: 1px;width: 960px;">
                <div id="smoothmenu1" class="ddsmoothmenu">
                    <?php
                    if (Zend_Auth::getInstance()->getIdentity()->id != null) :
                        switch (Zend_Auth::getInstance()->getIdentity()->usuario_grupo_id) :
                            case UsuarioGrupo::ADMINISTRADOR:
                                include_once APPLICATION_PATH . '/include/menu/administrador.php';
                                break;
                            case UsuarioGrupo::FUNCIONARIO:
                                include_once APPLICATION_PATH . '/include/menu/funcionario.php';
                                break;
                        endswitch;
                    endif;
                    ?>
                </div>
            </div>
        <?php endif; ?>
        <div style="margin-bottom: 20px;min-height: 390px;">
            <div style="width: 100%; margin-top: 130px;margin-bottom: -80px">

                <div class="body-content">

                    <div class="content">

                        <div class="rounded"  style=" width: 330px; margin: auto;">
                            <form action="<?php echo $this->baseUrl(); ?>/admin/auth/login" method="POST">
                                <table border="0">
                                    <tr>
                                        <td colspan="3" style="text-align: center;">
                                            <h4>Espaço ELA</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" style="font-size: 12px; text-align: center;">
                                            <?php echo $this->flashMessenger(); ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="right">
                                            <label class="control-label" for="usuario">Email:</label>
                                        </td>
                                        <td colspan="2">
                                            <input name="usuario" placeholder="Digite seu email" style="width: 250px;" class="text-input" type="text">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="right">
                                            <label class="control-label" for="senha">Senha:</label>
                                        </td>
                                        <td>
                                            <input name="senha" placeholder="Senha" style="width: 180px;" class="text-input" type="password">
                                        </td>
                                        <td>
                                            <input class="submit btn primary-btn flex-table-btn js-submit" type="submit" value="Entrar">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" style="font-size: 12px; font-family: 'Lucida Grande',Verdana,sans-serif; text-align: center; padding: 20px 0px 0px 0px">
                                            <ul style="list-style: none;">
                                                <li> <a style="color: #057ED0;" href="<?php echo $this->baseUrl() ?>/admin/conta/lembrarsenha/">Esqueceu sua senha?</a></li>
                                            </ul>
                                        </td>
                                    </tr>

                                </table>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div style=" width: 100%;bottom:0;background: #f9e8f9 url(/content/img/fundo.jpg)">
        <div style=" height: 60px;padding-top: 10px; text-align: center;position: relative">
            <?php include_once APPLICATION_PATH . '/include/footer_novo.php'; ?>
        </div>
    </div>

</div>

</body>
</html>

