<form id="form_pagamento" method="POST" action="" enctype="multipart/form-data">
    <fieldset>
        <?php echo $this->flashMessenger(); ?>
        <div class="row well">
            <div class="span4">
                <div class="control-group">
                    <label class="control-label" for="descricao">Descrição</label>
                    <div class="controls">
                        <input class="input-large" id="nome" name="descricao" type="text" value="<?php echo $this->pagamentoTipo->descricao ?>">
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="percentual">Percentual de Desconto</label>
                    <div class="controls">
                        <input class="input-small txValor" id="percentual" name="percentual" type="text" value="<?php echo AppUtil::convertFloatToString($this->pagamentoTipo->percentual) ?>">
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="control-group">
                    <label class="control-label" for="status">Status</label>
                    <div class="controls">
                        <select data-placeholder="[  Selecione o Status ]" class="input-small" name="status" id="status">
                            <option <?php echo ViewUtil::fillFieldSelect($this->pagamentoTipo->status, PagamentoTipo::ATIVO) ?> value="<?php echo PagamentoTipo::ATIVO ?>">Ativo</option>
                            <option <?php echo ViewUtil::fillFieldSelect($this->pagamentoTipo->status, PagamentoTipo::INATIVO) ?> value="<?php echo PagamentoTipo::INATIVO ?>">Inativo</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="span">
            <hr/>
        </div>
      </fieldset>


    <hr/>
    <div style="width: 100%;height: 20px">
        <div class="btn-concluir">
            <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/admin/pagamento-tipo/">Cancelar</a>
            <button type="submit" class="btn btn-success btn-large">Salvar</button>
        </div>
    </div>
</form>