<script type="text/javascript">

    $(document).ready(function() {
        //Quando carregar a pagina
        $(".dados").hide(); //esta primeira linha servirá para esconder as divs do conteúdo
        //$("#cultos li a:first").addClass("active").show(); //Ativar primeira aba
        //$(".horario:first").show('slow'); //abre a pagina suavemente
        var activeaba = '#data_cliente';
        $('#data_cliente').fadeIn('slow');
        //On Click Event
        $("#dados ul li a").click(function() {// quando clicar no link do menu irá executar a seguinte função:
            $("#dados ul li").removeClass("active"); //remove a class no link clicado para que não fica marcado
            $(this).parent().addClass("active"); //adiciona a classe no link clicado para que o usuario saiba em qual link ele esta
            $(".dados").hide(); //esconder as divs do conteúdo
            activeaba = $(this).attr("href"); //Encontrar o valor do atributo rel para identificar a aba que esta ativa + conteúdo
            $(activeaba).fadeIn('slow'); //efeito de fade in com o conteúdo ativo
            return false; // o returno falso evita que ao clicar no link a página role para o topo.
        });
    });
</script>
<?php echo $this->flashMessenger(); ?>

<form id="form_cliente" method="POST" action="" enctype="multipart/form-data">
    <fieldset>
        <div colspan="2">
            <div id="dados">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#data_cliente">Dados do Cliente</a></li>
                    <li><a href="#data_procedimentos">Procedimentos</a></li>
                </ul>
            </div>
        </div>
        <?php include 'cliente_dados.phtml'; ?>
        <?php include 'cliente_procedimentos.phtml'; ?>
    </fieldset>


    <hr/>
    <div style="width: 100%;height: 20px">
        <div class="btn-concluir">
            <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/funcionario/cliente/?nolayout=<?php echo $this->layout?>"">Cancelar</a>
            <button type="submit" class="btn btn-success btn-large">Salvar</button>
        </div>
    </div>
</form>
