<script type="text/javascript">

    $(document).ready(function() {
        //Quando carregar a pagina
        $(".dados").hide(); //esta primeira linha servirá para esconder as divs do conteúdo
        //$("#cultos li a:first").addClass("active").show(); //Ativar primeira aba
        //$(".horario:first").show('slow'); //abre a pagina suavemente
        var activeaba = '#form_empresa';
        $('#data_empresa').fadeIn('slow');
        //On Click Event
        $("#dados ul li a").click(function() {// quando clicar no link do menu irá executar a seguinte função:
            $("#dados ul li").removeClass("active"); //remove a class no link clicado para que não fica marcado
            $(this).parent().addClass("active"); //adiciona a classe no link clicado para que o usuario saiba em qual link ele esta
            $(".dados").hide(); //esconder as divs do conteúdo
            activeaba = $(this).attr("href"); //Encontrar o valor do atributo rel para identificar a aba que esta ativa + conteúdo
            $(activeaba).fadeIn('slow'); //efeito de fade in com o conteúdo ativo
            return false; // o returno falso evita que ao clicar no link a página role para o topo.
        });
    });


    function removeImagemButton(id) {
        $('#remove').attr('value', id);
        $('#form_empresa').submit();
    }
</script>


<form id="form_empresa" method="POST" action="" enctype="multipart/form-data">
    <fieldset>
        <?php echo $this->flashMessenger(); ?>
        <div id="data_empresa" class="dados" >
            <div class="row well">
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="razao_social">Razão Social</label>
                        <div class="controls">
                            <input class="input-xlarge" id="razao_social" name="razao_social" type="text" value="<?php echo $this->empresa->razao_social ?>">
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="nome_fantasia">Nome Fantasia</label>
                        <div class="controls">
                            <input class="input-xlarge" id="nome_fantasia" name="nome_fantasia" type="text" value="<?php echo $this->empresa->nome_fantasia ?>">
                        </div>
                    </div>
                </div>
                <div class="span3" style="float: right">
                    <div class="control-group">
                        <label class="control-label" for="logo">Logomarca</label>
                        <div class="controls">
                            <div class="row" >
                                <div id="result" style="background-color: #fff; margin: 10px 30px 10px 1px; padding: 5px;  float: left;" class="rounded-light shadow">
                                    <img src="<?php echo AppUtil::getFileView($this->empresa, 'e', '160') ?>">
                                </div>
                                <div class="input-append">
                                    <span class="btn success fileinput-button">
                                        <span>Selecionar imagem ...</span>
                                        <?php echo $this->form->file ?>
                                    </span>
                                    <?php if (AppUtil::isFileExists($this->empresa, 'e')) { ?>
                                        <a title="Remover imagem da logo" class="btn" onClick="removeImagemButton(<?php echo $this->empresa->id ?>);">
                                            <i class="icon-trash"></i>
                                        </a>
                                        <input type="hidden" name="remove" id="remove">
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="cnpj">CNPJ</label>
                        <div class="controls">
                            <input class="input-xlarge txCnpj" id="cnpj" name="cnpj" type="text" value="<?php echo ($this->empresa->cnpj) ?>" autocomplete="off">
                        </div>
                    </div>
                </div>
                <div class="span8">
                    <div class="control-group">
                        <label class="control-label" for="status">Status</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Status ]" class="input-xlarge" name="status" id="status">
                                <option <?php echo ViewUtil::fillFieldSelect($this->empresa->status, Empresa::ATIVA) ?> value="<?php echo Empresa::ATIVA ?>">Ativa</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->empresa->status, Empresa::INATIVA) ?> value="<?php echo Empresa::INATIVA ?>">Inativa</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="telefone_1">Celular 1</label>
                        <div class="controls">
                            <input class="input-xlarge txCelular" id="telefone_1" name="telefone_1" type="text" value="<?php echo AppUtil::convertIntToCelular($this->empresa->Endereco[0]->telefone_1) ?>">
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="telefone_2">Celular 2</label>
                        <div class="controls">
                            <input class="input-xlarge txCelular" id="telefone_2" name="telefone_2" type="text" value="<?php echo AppUtil::convertIntToCelular($this->empresa->Endereco[0]->telefone_2) ?>">
                        </div>
                    </div>
                </div>

            </div>
            <hr>
            <div class="row well">
                <div class="span4 ">
                    <div class="control-group">
                        <label class="control-label" for="cep">CEP</label>
                        <div class="controls">
                            <input class="input-xlarge txCep endereco" placeholder="_____-___" id="cep" name="cep" type="text" value="<?php echo $this->empresa->Endereco[0]->cep ?>">
                            <img id="loading_cep" style="display: none;" src="<?php echo $this->baseUrl() ?>/content/img/loading.gif" />
                            <span id="erro_cep" style="display: none">Cep não encontrado</span>
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="logradouro">Endereço</label>
                        <div class="controls">
                            <input class="input-xlarge endereco" id="logradouro" name="logradouro" type="text" value="<?php echo $this->empresa->Endereco[0]->logradouro ?>">
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="numero">Nº</label>
                        <div class="controls">
                            <input class="input-small endereco" id="numero" name="numero" type="text" value="<?php echo $this->empresa->Endereco[0]->numero ?>">
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="bairro">Bairro</label>
                        <div class="controls">
                            <input class="input-xlarge endereco" id="bairro" name="bairro" type="text" value="<?php echo $this->empresa->Endereco[0]->bairro ?>">
                        </div>
                    </div>
                </div>

                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="cidade">Cidade</label>
                        <div class="controls">
                            <input class="input-xlarge endereco" id="cidade" name="cidade" type="text" value="<?php echo $this->empresa->Endereco[0]->cidade ?>">
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="estado">UF</label>
                        <div class="controls">
                            <input class="input-small endereco" id="estado" maxlength="2"name="estado" type="text" value="<?php echo $this->empresa->Endereco[0]->estado ?>">
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="control-group">
                        <label class="control-label" for="complemento_endereco">Complemento Endereço</label>
                        <div class="controls">
                            <input class="input-xxlarge " id="complemento_endereco" name="complemento_endereco" type="text" value="<?php echo $this->empresa->Endereco[0]->complemento_endereco ?>">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>


    <hr/>
    <div style="width: 100%;height: 20px">
    <div class="btn-concluir">
        <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/admin/empresa/">Cancelar</a>
        <button type="submit" class="btn btn-success btn-large">Salvar</button>
    </div>
    </div>
</form>

<script src="<?php echo $this->baseUrl(); ?>/content/upload/jquery/js/load-image.min.js"></script>
<script type="text/javascript">
    var result = $('#result');

    document.getElementById('file').onchange = function(e) {
        window.loadImage(
            (e.dataTransfer || e.target).files[0],
            function(img) {
                result.children().replaceWith(img);
            },
            {
                maxWidth: 160,
                maxHeight: 160,
                canvas: true
            }
        );
    };


    function format_cep(cep) {
        cep = cep.replace(".", "");
        cep = cep.replace("-", "");
        cep = cep.replace(" ", "");
        cep = cep.replace(/_/g, "");
        return cep;
    }



    function format_string(str) {
        if (str == null)
            return '';
        str = str.replace(/-/g, " ");
        return str;
    }


    $("#cep").keyup(function(e) {

        var cep = format_cep($(this).val());
        if (cep.length < 8)
            return false;
        $('#data_fornecedor .endereco').attr('readonly', true);
        $('#erro_cep').hide();

        $.getJSON('<?php echo $this->baseUrl(); ?>/ajax/busca-cep/busca-cep', {cep: cep},
            function(endereco) {
                var data = jQuery.parseJSON(endereco);
                if (data.resultado == 1) {
                    $('#erro_cep').hide();
                    $("#logradouro").val(format_string(data.logradouro));
                    $("#numero").val('');
                    $("#bairro").val(format_string(data.bairro));
                    $("#cidade").val(format_string(data.cidade));
                    $("#estado").val(format_string(data.uf));
                    $("#numero").focus();
                    $('#loading_cep').hide();

                } else if (data.resultado == 0) {
                    $("#logradouro").val('');
                    $("#numero").val('');
                    $("#bairro").val('');
                    $("#cidade").val('');
                    $("#estado").val('');
                    $("#logradouro").focus();
                    $('#erro_cep').show('slow');
                }
                $('#data_fornecedor .endereco').attr('readonly', false);

            }, "json"
        );
    });
</script>