<div id="esquerda">
    <div style="margin: 10px">
        <div class="cabecalho-impressao" style="display: none">
            <h4 style="text-align: center"><?php echo $this->escola->nome_fantasia ?></h4>
            <p style="text-align: center;">CNPJ: <?php echo AppUtil::convertIntToCNPJ($this->escola->cnpj) ?></p>

            <img  style="float: left;height: 80px;margin-top: -45px;width: 70px;border: none;padding: 4px" src="<?php echo AppUtil::getFileView($this->escola, 'e', '80') ?>">
            <div style="margin: auto;width: 50%;margin-top: -10px">
                <p style="text-align: center">Rua <?php echo $this->escola->Unidade[0]->Endereco[0]->logradouro ?>, N° <?php echo $this->escola->Unidade[0]->Endereco[0]->numero ?> — Bairro <?php echo $this->escola->Unidade[0]->Endereco[0]->bairro ?>, <?php echo $this->escola->Unidade[0]->Endereco[0]->cidade ?> - <?php echo $this->escola->Unidade[0]->Endereco[0]->estado ?></p>
            </div>

            <div style="margin: auto;width: 50%;">
                <h4 style="text-align: center;">Boletos Emitidos</h4>
            </div>
        </div>


        <form id="form_boletos" method="POST" action="" enctype="multipart/form-data">
            <fieldset>
                <?php echo $this->flashMessenger(); ?>
                <div class="row well noprint">
                    <div class="span4">
                        <div class="control-group">
                            <label class="control-label" for="banco">Conta</label>
                            <div class="controls">
                                <select  class="input-xlarge" name="banco" id="banco">
                                    <option value="0">[ Selecione a Conta ]</option>
                                    <?php foreach ($this->contas as $conta_bancaria): ?>
                                        <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('banco'), $conta_bancaria->id) ?> value="<?php echo $conta_bancaria->id ?>"><?php echo $conta_bancaria->descricao ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="span5">
                        <div class="control-group">
                            <label>&nbsp;</label>
                            <span class="control-label" for="data_inicial">Exibir boletos de</span>
                            <input class="txData input-small" id="data_inicial" name="data_inicial" type="text" value="<?php echo $this->repository_filter->getParamByField('data_inicial') ?>">

                            <span class="control-label" for="data_final">até</span>
                            <input class="txData input-small" id="data_final" name="data_final" type="text" value="<?php echo $this->repository_filter->getParamByField('data_final') ?>">
                        </div>
                    </div> 
                    <div class="control-group">
                        <label class="control-label">&nbsp;</label>
                        <div class="controls">
                            <button type="submit" class="btn btn-info"><i class="icon-filter icon-white"></i>Filtrar</button>
                            <a class=" btn btn-inverse " href="javascript:self.print()"><i class="icon-print icon-white"></i>Imprimir</a>
                        </div>
                    </div>

                    <div class="span4">
                        <div class="control-group">
                            <label class="control-label" for="alunos">Alunos</label>
                            <div class="controls">
                                <div class="input-append">
                                    <select data-placeholder="[ Selecione o Aluno ]" class="span11 chzn-select" name="alunos[]" id="alunos" multiple="multiple">
                                        <option value="0"></option>
                                        <?php foreach ($this->alunos as $aluno): ?>
                                            <option <?php echo ViewUtil::fillFieldSelectMultiple($this->alunos_list, $aluno['id']) ?>  value="<?php echo $aluno['id'] ?>"><?php echo $aluno['nome'] ?> </option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>                   
                </div>

            </fieldset>

            <div class="cabecalho-impressao" style="margin: auto;text-align: center;width: 50%;display: none">
                <p>Período: 
                    <b style="text-decoration: underline "><?php echo AppUtil::convertDateToString($this->data_inicial) ?></b>
                    <?php if ($this->data_final != NULL) { ?>
                        a <b style="text-decoration: underline "><?php echo AppUtil::convertDateToString($this->data_final) ?></b>
                    <?php } ?>
                </p>
            </div>
            <?php if ($this->banco_obj != "" ) { ?>
                <div style="display: none" class="cabecalho-impressao">
                    <p><b>Conta: </b><?php echo $this->banco_obj ?></p>
                </div>
            <?php } ?>
            <?php if ($this->alunos_list != NULL) { ?>
                <div style="display: none" class="cabecalho-impressao">
                    <p><b>Alunos:</b> 
                        <?php foreach ($this->alunos_obj as $alunos): ?>
                           <?php echo $alunos['nome'] ?>,
                        <?php endforeach; ?>
                    </p>
                </div>
            <?php } ?>
            
            <hr/>
        </form>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Dt Venc</th>
                    <th>Valor</th>
                    <th>Descrição</th>  
                    <th>Aluno</th>
                    <th>Dt Pag</th>
                    <th>Pago</th>
                    <th>Juros</th>
                    <th>Multa</th>
                    <th>Taxa</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->list as $item): ?>
                    <tr style="color: blue">
                        <?php $total_valor += $item->pagamento_valor;
                        $total_juros += $item->pagamento_juros;
                        $total_multa += $item->pagamento_multa;
                        $total_taxa += $item->pagamento_taxa; ?>
                        <?php $total_saida += AppUtil::convertLancamentoDespesa($item) ?>
                        <td><a href="<?php echo $this->baseUrl(); ?>/financeiro/lancamento/editar/id/<?php echo $item->id; ?>"><?php echo AppUtil::convertDateToString($item->vencimento_data) ?></a></td>
                        <td class="valores">R$ <?php echo AppUtil::convertFloatToString($item->vencimento_valor,'.') ?></td>
                        <td style="text-transform: uppercase;">
                            <?php echo AppUtil::resumeTexto($item->descricao, 15) ?>
                        </td>
                        <td style="text-transform: uppercase;">                              
                       <?php echo AppUtil::resumeTexto($item->Aluno->nome, 30) ?>
                        </td>
                        <td><?php echo AppUtil::convertDateToString($item->pagamento_data) ?></td>
                        <td class="valores">R$ <?php echo AppUtil::convertFloatToString($item->pagamento_valor,'.') ?></td>                    
                        <td >R$ <?php echo AppUtil::convertFloatToString($item->pagamento_juros, '.') ?></td>
                        <td >R$ <?php echo AppUtil::convertFloatToString($item->pagamento_multa,'.') ?></td>
                        <td style="color: red">R$ <?php echo AppUtil::convertFloatToString($item->pagamento_taxa,'.') ?></td>
                    </tr>
               <?php endforeach; ?>
                <tr>
                    <td colspan="9">&nbsp</td>
                </tr>
                <tr style="font-weight:bold">
                    <td colspan="5">TOTAL</td>
                    <td  style="color: blue;" >R$ <?php echo AppUtil::convertFloatToString($total_valor,'.') ?></td>
                    <td  style="color: blue;" >R$ <?php echo AppUtil::convertFloatToString($total_juros,'.') ?></td>
                    <td  style="color: blue;" >R$ <?php echo AppUtil::convertFloatToString($total_multa,'.') ?></td>
                    <td  style="color: red;" >R$ <?php echo AppUtil::convertFloatToString($total_taxa,'.') ?></td>
                </tr>

            </tbody>
        </table>
        <div style="float: right;display: none" class="cabecalho-impressao"> <p>Emitido dia: <?php echo date('d/m/Y H:i:s') ?></p></div>
    </div>
    <div class="cabecalho-impressao" style="display: none;margin: auto;width: 150px;height: 20px;margin-top: 20px">         
        <img  style="height: 13px;width: 115px;opacity: 0.6;" src="<?php echo $this->baseUrl(); ?>/content/img/sbrasil.png">
    </div>
</div>