<script type="text/javascript">

    $(document).ready(function() {
        //Quando carregar a pagina
        $(".dados").hide(); //esta primeira linha servirá para esconder as divs do conteúdo
        //$("#cultos li a:first").addClass("active").show(); //Ativar primeira aba
        //$(".horario:first").show('slow'); //abre a pagina suavemente
        var activeaba = '#procedimento_dados';
        $('#procedimento_dados').fadeIn('slow');
        //On Click Event
        $("#dados ul li a").click(function() {// quando clicar no link do menu irá executar a seguinte função:
            $("#dados ul li").removeClass("active"); //remove a class no link clicado para que não fica marcado
            $(this).parent().addClass("active"); //adiciona a classe no link clicado para que o usuario saiba em qual link ele esta
            $(".dados").hide(); //esconder as divs do conteúdo
            activeaba = $(this).attr("href"); //Encontrar o valor do atributo rel para identificar a aba que esta ativa + conteúdo
            $(activeaba).fadeIn('slow'); //efeito de fade in com o conteúdo ativo
            return false; // o returno falso evita que ao clicar no link a página role para o topo.
        });
    });
</script>
<?php echo $this->flashMessenger(); ?>

<form id="form_procedimento" method="POST" action="" enctype="multipart/form-data">
    <fieldset>
        <div colspan="2">
            <div id="dados">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#procedimento_dados">Dados do Procedimento</a></li>
                    <li><a href="#procedimento_detalhes">Ficha Anamnese</a></li>
                </ul>
            </div>
        </div>
        <?php include 'procedimento_dados.phtml'; ?>
        <?php include 'procedimento_detalhes.phtml'; ?>
    </fieldset>


    <hr/>
    <div style="width: 100%;height: 20px">
        <div class="btn-concluir">
            <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/admin/procedimento/">Cancelar</a>
            <button type="submit" class="btn btn-success btn-large">Salvar</button>
        </div>
    </div>
</form>
