<style>
    .valores{width: 100px}
</style>
<div id="esquerda">
    <div style="margin: 10px">
        <div class="cabecalho-impressao" style="display: none">
            <h5 style="text-align: center"><?php echo $this->empresa->nome_fantasia ?></h5>
            <p style="text-align: center;">CNPJ: <?php echo AppUtil::convertIntToCNPJ($this->empresa->cnpj) ?></p>
            <img  style="float: left;height: 50px;margin-top: -45px;width: 50px;border: none;padding: 4px" src="<?php echo AppUtil::getFileView($this->empresa, 'e', '100') ?>">
            <div style="margin: auto;width: 50%;margin-top: -10px">
                <p style="text-align: center"><?php echo $this->empresa->Endereco[0]->logradouro ?>, N°: <?php echo $this->empresa->Endereco[0]->numero ?> — <?php echo $this->empresa->Endereco[0]->bairro ?>, <?php echo $this->empresa->Endereco[0]->cidade ?> - <?php echo $this->empresa->Endereco[0]->estado ?></p>
            </div>
            <div style="margin: auto;width: 50%;">
                <h5 style="text-align: center;">Clientes à Confirmar</h5>
            </div>
        </div>


        <form id="form_extrato" method="POST" action="" enctype="multipart/form-data">
            <fieldset>
                <?php echo $this->flashMessenger(); ?>
                <div class="row well noprint">
                    <div class="page-header" >
                        <h3>Clientes à Confirmar</h3>
                    </div>
                    <div class="row">
                        <div class="control-group">
                            <div class="controls">
                                <a class=" btn btn-inverse " href="javascript:self.print()"><i class="icon-print icon-white"></i>Imprimir</a>
                            </div>
                        </div>
                    </div>

            </fieldset>

         <hr/>
        </form>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Qt</th>
                <th>Nome</th>
                <th>Data Procedimento.</th>
                <th>Horario</th>
                <th>Procedimento</th>
                <th>Telefone</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php $count =1; foreach ($this->list as $item): ?>
                <tr>
                    <td><?php echo $count?></td>
                    <td style="text-transform: uppercase;"><b><a target="_blank" href="<?php echo $this->baseUrl()?>/admin/procedimento-cilios/editar/id/<?php echo $item->id ?>"><?php echo $item->Cliente->nome ." ".$item->Cliente->sobrenome?></a></b></td>
                    <td><?php echo AppUtil::convertDateToString($item->data) ?></td>
                    <td><?php echo AppUtil::convertDateToString($item->horario) ?></td>
                    <td><?php echo $item->ProcedimentoTipo->descricao ." - ".$item->ProcedimentoTipo->getTipo()?></td>
                    <td><?php echo AppUtil::convertIntToCelular($item->Cliente->Endereco[0]->telefone_1)?></td>
                    <td width="20px" style="text-align: center; vertical-align: middle;">
                        <a href="<?php echo $this->baseUrl(); ?>/admin/procedimento-cilios/confirmar/id/<?php echo $item->id; ?>"><i title="Confirmar Procedimento" class="icon-check"></i></a>
                    </td>
                </tr>
                <?php $count++?>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div style="float: right;display: none" class="cabecalho-impressao"> <p>Emitido dia: <?php echo date('d/m/Y H:i:s') ?></p></div>
    </div>
    <div class="cabecalho-impressao" style="display: none;margin: auto;width: 150px;height: 20px;margin-top: 20px">
        <img  style="height: 30px;width: 100px;opacity: 0.6;" src="<?php echo $this->baseUrl(); ?>/content/img/logo_holy.png">
    </div>
</div>
