<form id="form_ponto" method="POST" action="" enctype="multipart/form-data">
    <fieldset>
        <?php echo $this->flashMessenger(); ?>
        <div class="row well">
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="funcionario">Funcionario</label>
                    <div class="controls">
                        <select  data-placeholder="[ Selecione o Cliente ]" class="input-large chzn-select-deselect" name="funcionario" id="funcionario">
                            <option value="0"></option>
                            <?php foreach ($this->funcionarios as $funcionario): ?>
                                <option <?php echo ViewUtil::fillFieldSelect($this->registroPonto->usuario_id, $funcionario->id) ?> value="<?php echo $funcionario->id ?>"><?php echo $funcionario->nome . " ". $funcionario->sobrenome?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="data">Data</label>
                    <div class="controls">
                        <div class="input-append">
                            <input class="input-small txData" id="data" placeholder="__/__/____"name="data" type="text"  value="<?php echo AppUtil::convertDateTimeToString($this->registroPonto->ponto,'date') ?>">
                            <span class="add-on"><span class="icon-calendar"></span></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span2">
                <div class="control-group">
                    <label class="control-label" for="time">Horario</label>
                    <div class="controls">
                        <div class="input-append">
                            <input class="input-small " id="time" placeholder="__/__/____"name="time" type="text"  value="<?php echo AppUtil::convertDateTimeToString($this->registroPonto->ponto,'time') ?>">
                            <span class="add-on"><span class="icon-clock"></span></span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </fieldset>


    <hr/>
    <div style="width: 100%;height: 20px">
        <div class="btn-concluir">
            <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/admin/ponto/">Cancelar</a>
            <button type="submit" class="btn btn-success btn-large">Salvar</button>
        </div>
    </div>

</form>
