<script type="text/javascript">
    $(function() {
        $(".popup_extrato").colorbox({
            iframe: true,
            width: "90%",
            height: "90%",
            fixed: true,
            opacity: 0.8
        });


        $(".popup_liquidar").colorbox({
            iframe: true,
            width: "65%",
            height: "60%",
            fixed: true,
            opacity: 0.8,
            onClosed: function() {
                location.reload();
            }
        });



    });

</script>
<div id="esquerda">
    <div style="margin: 10px">

        <a style="float: right;" class="btn btn-success btn-large" href="<?php echo $this->baseUrl(); ?>/admin/lancamento/novo/">
            <i class="icon-plus icon-white"></i> Novo </a>

        <button style="float: right; margin-right: 5px;"  type="button" id="btn_filtrar" class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtro</button>

        <div class="page-header" >
            <h2>Lançamentos</h2>
        </div>
        <form method="GET" action="" style="display: none;" id="form_filtrar">
            <div class="row well">
                <a id="btn_close" class="close" href="#">&times;</a>

                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="descricao">Descrição</label>
                        <div class="controls">
                            <input class="input-large" placeholder="Descrição do Lançamento" id="descricao_lancamento" name="descricao" type="text" value="<?php echo $this->repository_filter->getParamByField('descricao') ?>">
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="tipo">Tipo</label>
                        <div class="controls">
                            <select data-placeholder="[ Todos ]" class="input-large chzn-select-deselect" name="tipo" id="tipo">
                                <option value="0"></option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('tipo'), Lancamento::RECEITA) ?> value="<?php echo Lancamento::RECEITA ?>">Receita</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('tipo'), Lancamento::DESPESA) ?> value="<?php echo Lancamento::DESPESA ?>">Despesa</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="pagamento">Forma de Pagamento</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Pagamento ]" class="input-large chzn-select-deselect" name="pagamento" id="pagamento">
                                <option value="0"></option>
                                <?php foreach ($this->pagamentos as $pagamento): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('pagamento'), $pagamento->id) ?> value="<?php echo $pagamento->id ?>"><?php echo $pagamento->descricao?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="cliente">Cliente</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Cliente ]" class="input-xlarge chzn-select-deselect" name="cliente" id="cliente">
                                <option value="0"></option>
                                <?php foreach ($this->clientes as $cliente): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('cliente'), $cliente->id) ?> value="<?php echo $cliente->id ?>"><?php echo $cliente->nome ." ".$cliente->sobrenome?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="situacao">Situação</label>
                        <div class="controls">
                            <select data-placeholder="[ Todos ]" class="input-large chzn-select-deselect" name="situacao" id="situacao">
                                <option value="0"></option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('situacao'), Lancamento::ABERTO) ?> value="<?php echo Lancamento::ABERTO ?>">Aberto</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('situacao'), Lancamento::LIQUIDADO) ?> value="<?php echo Lancamento::LIQUIDADO ?>">Liquidado</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('situacao'), Lancamento::VENCIDO) ?> value="<?php echo Lancamento::VENCIDO ?>">Vencido</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="conta_bancaria">Conta Bancaria</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione a Conta ]" class="input-large chzn-select-deselect" name="conta_bancaria" id="conta_bancaria">
                                <option value="0"></option>
                                <?php foreach ($this->contas as $conta): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('conta_bancaria'), $conta->id) ?> value="<?php echo $conta->id ?>"><?php echo $conta->descricao?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="fornecedor">Fornecedores</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Fornecedor ]" class="input-xlarge chzn-select-deselect" name="fornecedor" id="fornecedor">
                                <option value="0"></option>
                                <?php foreach ($this->fornecedores as $fornecedor): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('fornecedor'), $fornecedor->id) ?> value="<?php echo $fornecedor->id ?>"><?php echo $fornecedor->descricao?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span11">
                    <hr/>
                    <button type="submit" data-loading-text="Filtrando..." class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtrar</button>
                </div>

            </div>
        </form>

        <?php echo $this->flashMessenger(); ?>


        <ul class="pagination" style=" float: right;">

            <?php $url_part = (isset($this->repository_filter)) ? $this->repository_filter->getParamString(array("ano", "mes")) : ''; ?>

            <?php if ($this->params['mes'] <= 1) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] - 1 ?>&mes=12<?php echo $url_part ?>">&larr;</a></li>
            <?php } else { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] ?>&mes=<?php echo $this->params['mes'] - 1 ?><?php echo $url_part ?>">&larr;</a></li>
            <?php } ?>

            <?php foreach ($this->meses as $mes) : ?>
                <li class="<?php echo ($mes['id'] == $this->params['mes']) ? "active" : "number" ?>"><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] ?>&mes=<?php echo $mes['id'] ?><?php echo $url_part ?>"><?php echo AppUtil::getSmallMonth($mes['id']) ?></a></li>
            <?php endforeach; ?>


            <?php if ($this->params['mes'] >= 12) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] + 1 ?>&mes=1<?php echo $url_part ?>">&rarr;</a></li>
            <?php } else { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] ?>&mes=<?php echo $this->params['mes'] + 1 ?><?php echo $url_part ?>">&rarr;</a></li>
            <?php } ?>

        </ul>

        <ul class="pagination" style="margin-right: 20px; float: right;">
            <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] - 1 ?>&mes=<?php echo $this->params['mes'] ?>">&larr;</a></li>
            <li class="active"><a href="#"><?php echo $this->params['ano'] ?></a></li> 
            <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] + 1 ?>&mes=<?php echo $this->params['mes'] ?>">&rarr;</a></li>
        </ul>
        <form id="form-imprimir-boletos" method="POST" target="_blank">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th><?php echo ViewUtil::getOrderBy('Venc', 'vencimento_data', $this->repository_order) ?></th>
                        <th><?php echo ViewUtil::getOrderBy('Forma Pg', 'pt.descricao', $this->repository_order) ?></th>
                        <th><?php echo ViewUtil::getOrderBy('Valor Pg', 'vencimento_valor', $this->repository_order) ?></th>
                        <th><?php echo ViewUtil::getOrderBy('Valor Rec', 'pagamento_valor', $this->repository_order) ?></th>
                        <th><?php echo ViewUtil::getOrderBy('Descrição', 'descricao', $this->repository_order) ?></th>
                        <th>Cliente/Fornecedor</th>
                        <th>Situação</th>
                        <th></th>
                        <th colspan="3"></th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($this->list as $item): ?>
                        <?php ($item->tipo == Lancamento::RECEITA && $item->pagamento_data =! NULL  && $item->pagamento_valor > 0 ? $total_entrada += $item->pagamento_valor: $total_entrada)?>
                        <?php ($item->tipo == Lancamento::DESPESA && $item->pagamento_data =! NULL ? $total_saida += $item->pagamento_valor: $total_saida)?>
                        <tr style="color: <?php echo ($item->tipo == Lancamento::RECEITA) ? "blue" : "red" ?>;background-color:<?php echo ($item->getVencido() ? "#f4d6d7" : "") ?>">
                            <td style="width: 80px; "><?php echo AppUtil::convertDateToString($item->vencimento_data) ?></td>
                            <td style="width: 125px;"><?php echo $item->PagamentoTipo->descricao ?></td>
                            <td style="width: 80px !important">R$ <?php echo AppUtil::convertFloatToString($item->vencimento_valor,'.') ?></td>
                            <td style="width: 80px;">R$ <?php echo AppUtil::convertFloatToString($item->pagamento_valor,'.') ?></td>
                            <td style="width: 250px"><?php echo AppUtil::resumeTexto($item->descricao, 25) ?>  <?php echo $item->descricao_recorrencia?></td>
                            <td style="width: 250px">
                                <?php if ($item->cliente_id != NULL) {?>
                                <a href="<?php echo $this->baseUrl(); ?>/funcionario/cliente/editar/id/<?php echo $item->cliente_id; ?>" target="_blank">
                                    <?php echo AppUtil::resumeTexto($item->Cliente->getFullNome(),30)?>
                                </a>
                                <?php } else {?>
                                    <a href="<?php echo $this->baseUrl(); ?>/admin/fornecedor/editar/id/<?php echo $item->fornecedor_id; ?>">
                                        <?php echo $item->Fornecedor->descricao?>
                                    </a>
                                <?php }?>
                            </td>
                            <td>
                                <?php if ($item->pagamento_data != null) { ?>
                                    <span class="label label-success">Liquidado</span>
                                <?php } else { ?>
                                    <span class="label label-info">Á Pagar</span>
                                <?php } ?>
                            </td>
                            <?php if($item->pagamento_data == NULL){?>
                            <td width="20px" style="text-align: center; vertical-align: middle;">
                                <a class="popup_liquidar" title="Baixar Titulo" href="<?php echo $this->baseUrl(); ?>/admin/liquidar/lancamento/id/<?php echo $item->id; ?>"><i title="Liquidar Lançamento" class="icon-check"></i></a>
                            </td>
                            <?php } else { ?>
                                <td></td>
                            <?php } ?>
                            <td width="20px" style="text-align: center; vertical-align: middle;">
                                <a href="<?php echo $this->baseUrl(); ?>/admin/lancamento/editar/id/<?php echo $item->id; ?>"><i title="Editar Lançamento" class="icon-pencil"></i></a>
                            </td>
                            <td width="20px" style="text-align: center; vertical-align: middle;">
                                <a onclick="return confirm('Confirma a exclusão deste lançamento ?')" href="<?php echo $this->baseUrl(); ?>/admin/lancamento/deletar/id/<?php echo $item->id; ?>"><i title="Excluir Lançamento" class="icon-trash"></i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td colspan="10">&nbsp</td>
                    </tr>
                    <tr style="font-weight:bold">
                        <td colspan="4">TOTAL</td>
                        <td style="color: blue;">( + ) R$ <?php echo AppUtil::convertFloatToString($total_entrada,'.') ?></td>
                        <td  style="color: red;">( - ) R$ <?php echo AppUtil::convertFloatToString($total_saida,'.') ?></td>
                        <td colspan="4" style="color: black;">( = ) R$ <?php echo AppUtil::convertFloatToString($total_entrada-$total_saida,'.') ?></td>
                    </tr>
                </tbody>
            </table>
            <div class="noprint" style="width: 100%;height: 10px">
                <blockquote class="pull-right" >
                    <small style="background-color: #f2dede">Lançamento<strong> vencido </strong>&nbsp </small>
                </blockquote>
            </div>
        </form>
        <?php //if (isset($this->list)) echo $this->paginationControl($this->list, "All", "paginator.phtml", $this->list_params);  ?>

    </div>

</div>
