<script type="text/javascript">
    $(function() {
        $(".popup_extrato").colorbox({
            iframe: true,
            width: "90%",
            height: "90%",
            fixed: true,
            opacity: 0.8
        });

        $("#all_boleto_numero").click(function() {
            $('.boleto_numero').attr("checked", $(this).is(":checked"));
            $(".boleto_numero").change();
        });

        $("#imprimir-boletos").click(function() {
            $("#form-imprimir-boletos").submit();
            return false;
        });

        $(".boleto_numero").change(function() {
            if ($(".boleto_numero").is(":checked")) {
                $("#imprimir-boletos").attr("disabled", false);
            } else {
                $("#imprimir-boletos").attr("disabled", true);
            }
        }).trigger("change");

        if ($(".boleto_numero").length <= 0) {
            $("#all_boleto_numero").hide();
            $("#imprimir-boletos").hide();
        }


    });

</script>
<div id="esquerda">
    <div style="margin: 10px">

        <a style="float: right;" class="btn btn-success btn-large" href="<?php echo $this->baseUrl(); ?>/admin/lancamento/novo/">
            <i class="icon-plus icon-white"></i> Novo </a>

        <button style="float: right; margin-right: 5px;"  type="button" id="btn_filtrar" class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtro</button>

        <div class="page-header" >
            <h2>Lançamentos</h2>
        </div>
        <form method="GET" action="" style="display: none;" id="form_filtrar">
            <div class="row well">
                <a id="btn_close" class="close" href="#">&times;</a>

                <div class="span7">
                    <div class="control-group">
                        <label class="control-label" for="descricao">Descrição</label>
                        <div class="controls">
                            <input class="input-xxlarge" placeholder="Descrição do Lançamento" id="descricao_lancamento" name="descricao" type="text" value="<?php echo $this->repository_filter->getParamByField('descricao') ?>">
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="tipo">Tipo</label>
                        <div class="controls">
                            <select data-placeholder="[ Todos ]" class="input-medium chzn-select-deselect" name="tipo" id="tipo">
                                <option value="0"></option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('tipo'), Lancamento::RECEITA) ?> value="<?php echo Lancamento::RECEITA ?>">Receita</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('tipo'), Lancamento::DESPESA) ?> value="<?php echo Lancamento::DESPESA ?>">Despesa</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span7">
                    <div class="control-group">
                        <label class="control-label" for="cliente">Cliente</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Cliente ]" class="input-xxlarge chzn-select-deselect" name="cliente" id="cliente">
                                <option value="0"></option>
                                <?php foreach ($this->clientes as $cliente): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('cliente'), $cliente->id) ?> value="<?php echo $cliente->id ?>"><?php echo $cliente->nome ." ".$cliente->sobrenome?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="situacao">Situação</label>
                        <div class="controls">
                            <select data-placeholder="[ Todos ]" class="input-medium chzn-select-deselect" name="situacao" id="situacao">
                                <option value="0"></option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('situacao'), Lancamento::ABERTO) ?> value="<?php echo Lancamento::ABERTO ?>">Aberto</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('situacao'), Lancamento::LIQUIDADO) ?> value="<?php echo Lancamento::LIQUIDADO ?>">Liquidado</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('situacao'), Lancamento::VENCIDO) ?> value="<?php echo Lancamento::VENCIDO ?>">Vencido</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span11">
                    <hr/>
                    <button type="submit" data-loading-text="Filtrando..." class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtrar</button>
                </div>

            </div>
        </form>

        <?php echo $this->flashMessenger(); ?>


        <ul class="pagination" style=" float: right;">

            <?php $url_part = (isset($this->repository_filter)) ? $this->repository_filter->getParamString(array("ano", "mes")) : ''; ?>

            <?php if ($this->params['mes'] <= 1) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] - 1 ?>&mes=12<?php echo $url_part ?>">&larr;</a></li>
            <?php } else { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] ?>&mes=<?php echo $this->params['mes'] - 1 ?><?php echo $url_part ?>">&larr;</a></li>
            <?php } ?>

            <?php foreach ($this->meses as $mes) : ?>
                <li class="<?php echo ($mes['id'] == $this->params['mes']) ? "active" : "number" ?>"><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] ?>&mes=<?php echo $mes['id'] ?><?php echo $url_part ?>"><?php echo AppUtil::getSmallMonth($mes['id']) ?></a></li>
            <?php endforeach; ?>


            <?php if ($this->params['mes'] >= 12) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] + 1 ?>&mes=1<?php echo $url_part ?>">&rarr;</a></li>
            <?php } else { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] ?>&mes=<?php echo $this->params['mes'] + 1 ?><?php echo $url_part ?>">&rarr;</a></li>
            <?php } ?>

        </ul>

        <ul class="pagination" style="margin-right: 20px; float: right;">
            <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] - 1 ?>&mes=<?php echo $this->params['mes'] ?>">&larr;</a></li>
            <li class="active"><a href="#"><?php echo $this->params['ano'] ?></a></li> 
            <li><a href="<?php echo $this->baseUrl(); ?>/admin/lancamento?ano=<?php echo $this->params['ano'] + 1 ?>&mes=<?php echo $this->params['mes'] ?>">&rarr;</a></li>
        </ul>
        <form id="form-imprimir-boletos" method="POST" target="_blank">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th><?php echo ViewUtil::getOrderBy('Vencimento', 'vencimento_data', $this->repository_order) ?></th>
                        <th><?php echo ViewUtil::getOrderBy('Valor', 'vencimento_valor', $this->repository_order) ?></th>                    
                        <th><?php echo ViewUtil::getOrderBy('Descrição', 'descricao', $this->repository_order) ?></th>                    
                        <th><?php echo ViewUtil::getOrderBy('Cliente', 'c.nome', $this->repository_order) ?></th>
                        <th>Situação</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($this->list as $item): ?>
                        <tr style="color: <?php echo ($item->tipo == Lancamento::RECEITA) ? "blue" : "red" ?>; background-color:<?php echo ($item->vencimento_data_atualizada && $item->pagamento_data == NULL) ? "#d9edf7" : "" ?>;background-color:<?php echo ($item->getVencido() ? "#f4d6d7" : "") ?> ">

                            <td style="width: 80px; text-align: center;"><?php echo AppUtil::convertDateToString($item->getDataVencimentoAtual()) ?></td>
                            <td style="width: 75px !important">R$ <?php echo AppUtil::convertFloatToString($item->getValorVencimentoAtual(),'.') ?></td>
                            <td style="width: 250px"><?php echo AppUtil::resumeTexto($item->descricao, 25) ?>  <?php echo $item->descricao_recorrencia?></td>
                            <td style="width: 250px">
                                <a href="<?php echo $this->baseUrl(); ?>/funcionario/cliente/editar/id/<?php echo $item->cliente_id; ?>">
                                    <?php echo $item->Cliente->nome." ".$item->Cliente->sobrenome?>
                                </a>
                            </td>
                            <td style="width: 60px"><?php echo $item->getSituacao() ?></td>
                            <td width="20px" style="text-align: center; vertical-align: middle;">
                                <a href="<?php echo $this->baseUrl(); ?>/admin/lancamento/editar/id/<?php echo $item->id; ?>"><i title="Editar Lançamento" class="icon-pencil"></i></a>
                            </td>
                            <td width="20px" style="text-align: center; vertical-align: middle;">
                                <a onclick="return confirm('Confirma a exclusão deste lançamento ?')" href="<?php echo $this->baseUrl(); ?>/admin/lancamento/deletar/id/<?php echo $item->id; ?>"><i title="Excluir Lançamento" class="icon-trash"></i></a>
                            </td>

                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="noprint" style="width: 100%;height: 10px">
                <blockquote class="pull-right" >
                    <small style="background-color: #d9edf7">Lançamento<strong> atualizado </strong> &nbsp </small>
                    <small style="background-color: #f2dede">Lançamento<strong> vencido </strong>&nbsp </small>
                </blockquote>
            </div>
        </form>
        <?php //if (isset($this->list)) echo $this->paginationControl($this->list, "All", "paginator.phtml", $this->list_params);  ?>

    </div>

</div>
