<form id="form_unidade" method="POST" action="" enctype="multipart/form-data">
    <fieldset>
        <?php echo $this->flashMessenger(); ?>
        <div class="row well">


            <div class="span5">
                <div class="control-group">
                    <label class="control-label" for="descricao">Descrição</label>
                    <div class="controls">
                        <input class="input-xlarge" id="nome" name="descricao" type="text" value="<?php echo $this->banco->descricao ?>">
                    </div>
                </div>
            </div>
             <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="codigo">Código</label>
                    <div class="controls">
                        <input class="input-small" id="codigo" name="codigo" type="text" value="<?php echo $this->banco->codigo ?>">
                    </div>
                </div>
            </div>
         <div class="span2">
                <div class="control-group">
                    <label class="control-label" for="status">Status</label>
                    <div class="controls">
                        <select data-placeholder="[  Selecione o Status ]" class="input-small chzn-select-deselect" name="status" id="status">
                            <option <?php echo ViewUtil::fillFieldSelect($this->banco->status, Banco::ATIVO) ?> value="<?php echo Banco::ATIVO ?>">Ativo</option>
                            <option <?php echo ViewUtil::fillFieldSelect($this->banco->status, Banco::INATIVO) ?> value="<?php echo Banco::INATIVO ?>">Inativo</option>
                        </select>
                    </div>
                </div>
            </div>
           
        </div>
    </fieldset>


    <hr/>
    <div style="width: 100%;height: 20px">
    <div class="btn-concluir">
        <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/admin/banco/">Cancelar</a>
        <button type="submit" class="btn btn-success btn-large">Salvar</button>
    </div>
    </div>
</form>
