<?php

/**
 * DaoFornecedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descricao
 * @property string $email
 * @property string $cnpj
 * @property string $contato
 * @property integer $status
 * @property integer $empresa_id
 * @property integer $fornecedor_categoria_id
 * @property Empresa $Empresa
 * @property FornecedorCategoria $FornecedorCategoria
 * @property Doctrine_Collection $Endereco
 * @property Doctrine_Collection $Lancamento
 * @property Doctrine_Collection $Movimento
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class DaoFornecedor extends DaoGeneric
{
    public function setTableDefinition()
    {
        $this->setTableName('fornecedor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('descricao', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('email', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('cnpj', 'string', 14, array(
             'type' => 'string',
             'length' => 14,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('contato', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('empresa_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('fornecedor_categoria_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('FornecedorCategoria', array(
             'local' => 'fornecedor_categoria_id',
             'foreign' => 'id'));

        $this->hasMany('Endereco', array(
             'local' => 'id',
             'foreign' => 'fornecedor_id'));

        $this->hasMany('Lancamento', array(
             'local' => 'id',
             'foreign' => 'fornecedor_id'));

        $this->hasMany('Movimento', array(
             'local' => 'id',
             'foreign' => 'fornecedor_id'));
    }
}