<?php

/**
 * DaoLancamentoRecorrencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property Doctrine_Collection $Lancamento
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class DaoLancamentoRecorrencia extends DaoGeneric
{
    public function setTableDefinition()
    {
        $this->setTableName('lancamento_recorrencia');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Lancamento', array(
             'local' => 'id',
             'foreign' => 'lancamento_recorrencia_id'));
    }
}