<script type="text/javascript">
    $(function() {
        $(".popup_extrato").colorbox({
            iframe: true,
            width: "90%",
            height: "90%",
            fixed: true,
            opacity: 0.8
        });
    });

</script>
<div id="esquerda">
    <div style="margin: 10px">

        <a style="float: right;" class="btn btn-success btn-large" href="<?php echo $this->baseUrl(); ?>/funcionario/procedimento-massagem/novo/">
            <i class="icon-plus icon-white"></i> Novo </a>

        <button style="float: right; margin-right: 5px;"  type="button" id="btn_filtrar" class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtro</button>

        <div class="page-header" >
            <h2>Procedimentos Massagens</h2>
        </div>
        <form method="GET" action="" style="display: none;" id="form_filtrar">
            <div class="row well">
                <a id="btn_close" class="close" href="#">&times;</a>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="status">Status</label>
                        <div class="controls">
                            <select data-placeholder="[ Todos ]" class="input-medium chzn-select-deselect" name="status" id="status">
                                <option value="0"></option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('status'), Procedimento::REALIZADO) ?> value="<?php echo Procedimento::REALIZADO ?>">Realizado</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('status'), Procedimento::ABERTO) ?> value="<?php echo Procedimento::ABERTO ?>">Aberto</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('status'), Procedimento::CANCELADO) ?> value="<?php echo Procedimento::CANCELADO ?>">Cancelado</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="tipo">Tipo</label>
                        <div class="controls">
                            <select data-placeholder="[ tipo ]" class="input-medium chzn-select-deselect" name="tipo" id="tipo">
                                <option value="0"></option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('tipo'), ProcedimentoTipo::APLICACAO) ?> value="<?php echo ProcedimentoTipo::APLICACAO ?>">Aplicação</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('tipo'), ProcedimentoTipo::MANUTENCAO) ?> value="<?php echo ProcedimentoTipo::MANUTENCAO ?>">Manutenção</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('tipo'), ProcedimentoTipo::REMOCAO) ?> value="<?php echo ProcedimentoTipo::REMOCAO ?>">Remoção</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span2">
                    <div class="control-group">
                        <label class="control-label" for="procedimento_data">Data</label>
                        <div class="controls">
                            <div class="input-append">
                                <input class="input-small txData" id="procedimento_data" placeholder="__/__/____"name="procedimento_data" type="text"  value="<?php echo $this->repository_filter->getParamByField('procedimento_data') ?>">
                                <span class="add-on"><span class="icon-calendar"></span></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="span7">
                    <div class="control-group">
                        <label class="control-label" for="aluno">Cliente</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Cliente ]" class="input-xxlarge chzn-select-deselect" name="cliente" id="cliente">
                                <option value="0"></option>
                                <?php foreach ($this->clientes as $cliente): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('cliente'), $cliente->id) ?> value="<?php echo $cliente->id ?>"><?php echo $cliente->nome ." ".$cliente->sobrenome?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="span11">
                    <hr/>
                    <button type="submit" data-loading-text="Filtrando..." class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtrar</button>
                </div>

            </div>
        </form>

        <?php echo $this->flashMessenger(); ?>



        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><?php echo ViewUtil::getOrderBy('Data', 'data', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Horario', 'horario', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Cliente', 'c.nome', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Procedimento', 'procedimento_tipo_id', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Colaborador', 'usuario_id', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Status', 'status', $this->repository_order) ?></th>
                    <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->list as $item): ?>
                    <tr style="color: <?php echo ($item->status == Procedimento::ABERTO) ? "green" : "" ?>;color: <?php echo ($item->status == Procedimento::REALIZADO) ? "blue" : " " ?>;color: <?php echo ($item->status == Procedimento::CANCELADO) ? "red" : "" ?>; background-color:<?php echo ($item->status == Procedimento::ABERTO) ? "#d4f4d4" : "" ?>;background-color:<?php echo ($item->status == Procedimento::REALIZADO) ? "#d9edf7" : "" ?>;background-color:<?php echo ($item->status == Procedimento::CANCELADO) ? "#f4d6d7" : "" ?> ">
                        <td><?php echo AppUtil::convertDateToString($item->data) ?></td>
                            <td><?php echo $item->horario ?></td>
                            <td><?php echo $item->Cliente->nome." ".$item->Cliente->sobrenome?></td>
                            <?php if($item->procedimento_tipo_id != NULL){?>
                                <td><?php echo $item->ProcedimentoTipo->descricao. " - " .$item->ProcedimentoTipo->getTipo()?></td>
                            <?php } else {?>
                                <td></td>
                            <?php }?>
                            <td><?php echo $item->Usuario->nome?></td>
                            <td><?php echo $item->getStatus()?></td>
                            <?php if($item->status == Procedimento::ABERTO){?>
                            <td width="20px" style="text-align: center; vertical-align: middle;">
                                <a class="popup" title="Enviar Aprovação" href="<?php echo $this->baseUrl(); ?>/funcionario/procedimento-messagem/enviar/id/<?php echo $item->id; ?>"><i title="Enviar Aprovação" class="icon-envelope"></i></a>
                            </td>
                            <?php } else { ?>
                            <td></td>
                            <?php } ?>
                            <td width="20px" style="text-align: center; vertical-align: middle;">
                                <a href="<?php echo $this->baseUrl(); ?>/funcionario/procedimento-massagem/editar/id/<?php echo $item->id; ?>"><i title="Editar Procedimento" class="icon-pencil"></i></a>
                            </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php if (isset($this->list)) echo $this->paginationControl($this->list, "All", "paginator.phtml", $this->list_params);  ?>
    </div>
</div>
