<?php

/**
 * Banco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banco extends DaoBanco {

    const ATIVO = 1;
    const INATIVO = 2;
    
    const CEF = 104;
    const BRADESCO = 237;
    const BANCOOB = 756;
    
    

    public function getStatus() {
        switch ($this->status) {

            case Banco::ATIVO:
                return 'Ativo';

            case Banco::INATIVO:
                return 'Inativo';

            default:
                return 'Indefinido';
        }
    }

}
