<?php

/**
 * ContaBancaria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContaBancaria extends DaoContaBancaria
{
    const ATIVO = 1;
    const INATIVO = 2;
    const EXCLUIDO = 3;


    public function getStatus() {
        switch ($this->status) {

            case ContaBancaria::ATIVO:
                return 'Ativo';

            case ContaBancaria::INATIVO:
                return 'Inativo';

            case ContaBancaria::EXCLUIDO:
                return 'Excluido';

            default:
                return 'Indefinido';
        }
    }
}