<?php

/**
 * Escola
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Escola extends DaoEscola {

    const ATIVA = 1;
    const INATIVA = 2;
    const EXCLUIDO = 3;

    public function getStatus() {
        switch ($this->status) {

            case Escola::ATIVA:
                return 'Ativa';

            case Escola::INATIVA:
                return 'Inativa';

            case Escola::EXCLUIDO:
                return 'Excluído';

            default:
                return 'Indefinido';
        }
    }

    public function getSede() {

        $unidade = new Unidade();

        foreach ($this->Unidade as $unidade) {
            if ($unidade->sede == Unidade::SIM) {
                $result = $unidade;
                break;
            }
        }

        return $result;
    }

}
