<?php

/**
 * Fornecedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Fornecedor extends DaoFornecedor
{
    const ATIVO = 1;
    const INATIVO = 2;


    public function getStatus() {
        switch ($this->status) {

            case Fornecedor::ATIVO:
                return 'Ativo';

            case Fornecedor::INATIVO:
                return 'Inativo';

            default:
                return 'Indefinido';
        }
    }

}
