<?php

/**
 * LancamentoRecorrenciaTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LancamentoRecorrenciaTipo extends DaoLancamentoRecorrenciaTipo
{

    const ATIVO = 1;
    const INATIVO = 2;


    public function getStatus() {
        switch ($this->status) {

            case LancamentoRecorrenciaTipo::ATIVO:
                return 'Ativo';

            case LancamentoRecorrenciaTipo::INATIVO:
                return 'Inativo';

            default:
                return 'Indefinido';
        }
    }
}