<?php

/**
 * PlanoDeContas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PlanoDeContas extends DaoPlanoDeContas {

    const PAI = 1;
    const FILHO = 2;
        
    const ATIVO = 1;
    const INATIVO = 2;
    
    const CREDITO = 1;
    const DEBITO = 2;
    
    const ACERTO_SALDO = "Acerto de Saldo";
    const TRANSFERENCIA = "Transferencia";

    public function getTipo() {
        switch ($this->tipo) {

            case PlanoDeContas::PAI:
                return 'Pai';

            case PlanoDeContas::FILHO:
                return 'Filho';

            default:
                return 'Indefinido';
        }
    }
    
    public function getNatureza() {
        switch ($this->natureza_operacao) {

            case PlanoDeContas::CREDITO:
                return 'Credito';

            case PlanoDeContas::DEBITO:
                return 'Débito';

            default:
                return 'Indefinido';
        }
    }
    
      public function getStatus() {
        switch ($this->status) {

            case PlanoDeContas::ATIVO:
                return 'Ativo';

            case PlanoDeContas::INATIVO:
                return 'Inativo';

            default:
                return 'Indefinido';
        }
    }

}
