<?php

/**
 * ProcedimentoTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProcedimentoTipo extends DaoProcedimentoTipo
{

    const ATIVO = 1;
    const INATIVO = 2;
    const EXCLUIDO = 3;

    const APLICACAO = 1;
    const MANUTENCAO = 2;
    const REMOCAO = 3;


    public function getStatus() {
        switch ($this->status) {

            case ProcedimentoTipo::ATIVO:
                return 'Ativo';

            case ProcedimentoTipo::INATIVO:
                return 'Inativo';

            case ProcedimentoTipo::EXCLUIDO:
                return 'Excluido';

            default:
                return 'Indefinido';
        }
    }

    public function getTipo() {
        switch ($this->tipo) {

            case ProcedimentoTipo::APLICACAO:
                return 'Aplicação';

            case ProcedimentoTipo::MANUTENCAO:
                return 'Manutenção';

            case ProcedimentoTipo::REMOCAO:
                return 'Remoção';

            default:
                return 'Indefinido';
        }
    }
}