<?php

/**
 * Procedimento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Procedimento extends DaoProcedimento
{
    const REALIZADO = 1;
    const ABERTO = 2;
    const CANCELADO = 3;
    const EXCLUIDO = 4;


    public function getStatus() {
        switch ($this->status) {

            case Procedimento::REALIZADO:
                return 'Realizado';

            case Procedimento::ABERTO:
                return 'Aberto';

            case Procedimento::CANCELADO:
                return 'Cancelado';

            default:
                return 'Indefinido';
        }
    }

}