<?php

/**
 * Produto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Produto extends DaoProduto
{
    const ATIVO = 1;
    const INATIVO = 2;
    const EXCLUIDO = 3;

    const CURVATURA_C = 1;
    const CURVATURA_D = 2;


    public function getCurvatura() {
        switch ($this->curvatura) {

            case Produto::CURVATURA_C:
                return 'Curvatura C';

            case Produto::CURVATURA_D:
                return 'Curvatura D';

            default:
                return 'Indefinido';
        }
    }

    public function getStatus() {
        switch ($this->status) {

            case Produto::ATIVO:
                return 'Ativo';

            case Produto::INATIVO:
                return 'Inativo';

            default:
                return 'Indefinido';
        }
    }

}