<?php

/**
 * UsuarioGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UsuarioGrupo extends DaoUsuarioGrupo {

    const ADMINISTRADOR = 1;
    const FUNCIONARIO = 2;

    public function getFuncionalidades() {
        $funcionalidades = array();
        foreach ($this->UsuarioGrupoPermissao as $permissao) {
            if ($permissao->permitido)
                $funcionalidades[] = $permissao->usuario_grupo_permissao_funcionalidade_id;
        }
        return $funcionalidades;
    }

    public function getGrupo() {
        switch ($this->id) {

            case UsuarioGrupo::ADMINISTRADOR:
                return 'administrador';

            case UsuarioGrupo::FUNCIONARIO:
                return 'funcionario';

            default:
                return 'Indefinido';
        }
    }

}
