<div id="esquerda">
    <div style="margin: 10px">

        <a style="float: right;" class="btn btn-success btn-large" href="<?php echo $this->baseUrl(); ?>/admin/produto-compra/novo/">
            <i class="icon-plus icon-white"></i> Novo </a>

        <button style="float: right; margin-right: 5px;"  type="button" id="btn_filtrar" class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtro</button>

        <div class="page-header" >
            <h2>Entrada de Produtos</h2>
        </div>
        <form method="GET" action="" style="display: none;" id="form_filtrar">
            <div class="row well">
                <a id="btn_close" class="close" href="#">&times;</a>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="status">Status</label>
                        <div class="controls">
                            <select data-placeholder="[ Todos ]" class="input-medium chzn-select-deselect" name="status" id="status">
                                <option value="0"></option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('status'), Movimento::ABERTO) ?> value="<?php echo Movimento::ABERTO ?>">Aberto</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('status'), Movimento::REALIZADO) ?> value="<?php echo Movimento::REALIZADO ?>">Realizado</option>
                                <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('status'), Movimento::CANCELADO) ?> value="<?php echo Movimento::CANCELADO ?>">Cancelado</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="pagamento">Forma de Pagamento</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Pagamento ]" class="input-large chzn-select-deselect" name="pagamento" id="pagamento">
                                <option value="0"></option>
                                <?php foreach ($this->forma_pagamento as $pagamento): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('pagamento'), $pagamento->id) ?> value="<?php echo $pagamento->id ?>"><?php echo $pagamento->descricao?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="control-group">
                        <label class="control-label" for="fornecedor">Fornecedor</label>
                        <div class="controls">
                            <select data-placeholder="[ Selecione o Fornecedor ]" class="input-xxlarge chzn-select-deselect" name="fornecedor" id="fornecedor">
                                <option value="0"></option>
                                <?php foreach ($this->fornecedores as $fornecedor): ?>
                                    <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('fornecedor'), $fornecedor->id) ?> value="<?php echo $fornecedor->id ?>"><?php echo $fornecedor->descricao ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="span11">
                    <hr/>
                    <button type="submit" data-loading-text="Filtrando..." class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtrar</button>
                </div>

            </div>
        </form>

        <?php echo $this->flashMessenger(); ?>


        <ul class="pagination" style=" float: right;">

            <?php $url_part = (isset($this->repository_filter)) ? $this->repository_filter->getParamString(array("ano", "mes")) : ''; ?>

            <?php if ($this->params['mes'] <= 1) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/produto-compra?ano=<?php echo $this->params['ano'] - 1 ?>&mes=12<?php echo $url_part ?>">&larr;</a></li>
            <?php } else { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/produto-compra?ano=<?php echo $this->params['ano'] ?>&mes=<?php echo $this->params['mes'] - 1 ?><?php echo $url_part ?>">&larr;</a></li>
            <?php } ?>

            <?php foreach ($this->meses as $mes) : ?>
                <li class="<?php echo ($mes['id'] == $this->params['mes']) ? "active" : "number" ?>"><a href="<?php echo $this->baseUrl(); ?>/admin/produto-compra?ano=<?php echo $this->params['ano'] ?>&mes=<?php echo $mes['id'] ?><?php echo $url_part ?>"><?php echo AppUtil::getSmallMonth($mes['id']) ?></a></li>
            <?php endforeach; ?>


            <?php if ($this->params['mes'] >= 12) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/produto-compra?ano=<?php echo $this->params['ano'] + 1 ?>&mes=1<?php echo $url_part ?>">&rarr;</a></li>
            <?php } else { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/admin/produto-compra?ano=<?php echo $this->params['ano'] ?>&mes=<?php echo $this->params['mes'] + 1 ?><?php echo $url_part ?>">&rarr;</a></li>
            <?php } ?>

        </ul>

        <ul class="pagination" style="margin-right: 20px; float: right;">
            <li><a href="<?php echo $this->baseUrl(); ?>/admin/produto-compra?ano=<?php echo $this->params['ano'] - 1 ?>&mes=<?php echo $this->params['mes'] ?>">&larr;</a></li>
            <li class="active"><a href="#"><?php echo $this->params['ano'] ?></a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/admin/produto-compra?ano=<?php echo $this->params['ano'] + 1 ?>&mes=<?php echo $this->params['mes'] ?>">&rarr;</a></li>
        </ul>
        <form id="form-imprimir-boletos" method="POST" target="_blank">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th><?php echo ViewUtil::getOrderBy('Data Compra', 'data_movimento', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Fornecedor', 'fornecedor_id', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Valor', 'valor', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Forma Pg', 'pagamento_tipo_id', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Status', 'status', $this->repository_order) ?></th>
                    <th colspan="2"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->list as $item): ?>
                    <tr>
                        <td><?php echo AppUtil::convertDateToString($item->data_movimento) ?></td>
                        <td><?php echo $item->Fornecedor->descricao ?></td>
                        <td>R$ <?php echo AppUtil::convertFloatToString($item->valor,'.') ?></td>
                        <td><?php echo $item->PagamentoTipo->descricao ?></td>
                        <td><?php echo $item->getStatus()?></td>
                        <td width="20px" style="text-align: center; vertical-align: middle;">
                            <a href="<?php echo $this->baseUrl(); ?>/admin/produto-compra/editar/id/<?php echo $item->id; ?>"><i title="Editar Compra" class="icon-pencil"></i></a>
                        </td>
                        <td width="20px" style="text-align: center; vertical-align: middle;">
                            <a onclick="return confirm('Confirma a exclusão desta compra ?')" href="<?php echo $this->baseUrl(); ?>/admin/produto-compra/deletar/id/<?php echo $item->id; ?>"><i title="Excluir Lançamento" class="icon-trash"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </form>
        <?php //if (isset($this->list)) echo $this->paginationControl($this->list, "All", "paginator.phtml", $this->list_params);  ?>

    </div>

</div>
