<style>
    .valores{width: 100px}
</style>
<div id="esquerda">
    <div style="margin: 10px">
        <div class="cabecalho-impressao" style="display: none">
            <h5 style="text-align: center"><?php echo $this->empresa->nome_fantasia ?></h5>
            <p style="text-align: center;">CNPJ: <?php echo AppUtil::convertIntToCNPJ($this->empresa->cnpj) ?></p>
            <img  style="float: left;height: 50px;margin-top: -45px;width: 50px;border: none;padding: 4px" src="<?php echo AppUtil::getFileView($this->empresa, 'e', '100') ?>">
            <div style="margin: auto;width: 50%;margin-top: -10px">
                <p style="text-align: center"><?php echo $this->empresa->Endereco[0]->logradouro ?>, N°: <?php echo $this->empresa->Endereco[0]->numero ?> — <?php echo $this->empresa->Endereco[0]->bairro ?>, <?php echo $this->empresa->Endereco[0]->cidade ?> - <?php echo $this->empresa->Endereco[0]->estado ?></p>
            </div>
            <div style="margin: auto;width: 50%;">
                <h5 style="text-align: center;">Comissão Por Periodo</h5>
            </div>
        </div>
        <form id="form_extrato" method="POST" action="" enctype="multipart/form-data">
            <fieldset>
                <?php echo $this->flashMessenger(); ?>
                <div class="row well noprint">
                    <div class="page-header" >
                        <h2>Comissão por Colaborador</h2>
                    </div>
                    <div class="row">
                        <div class="control-group span5">
                            <label class="control-label">Periodo:</label>
                            <div class="controls">
                                <select class="span2" name="ano">
                                    <?php foreach ($this->anos as $ano) : ?>
                                        <option value="<?php echo $ano ?>" <?php echo ViewUtil::fillFieldSelect($ano, $this->params['ano']) ?>><?php echo $ano ?></option>
                                    <?php endforeach; ?>
                                </select>
                                <select class="span2" name="mes">
                                    <?php foreach ($this->meses as $mes) : ?>
                                        <option value="<?php echo $mes['id'] ?>" <?php echo ViewUtil::fillFieldSelect($mes['id'], $this->params['mes']) ?>><?php echo $mes['text'] ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    <div class="span4">
                        <div class="control-group">
                            <label class="control-label" for="colaborador">Colaborador</label>
                            <div class="controls">
                                <select data-placeholder="[  Selecione o Colaborador ]" class="input-xlarge chzn-select-deselect" name="colaborador" id="colaborador">
                                    <option value="0"></option>
                                    <?php foreach ($this->colaboradores as $colaborador): ?>
                                        <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('colaborador'), $colaborador->id) ?> value="<?php echo $colaborador->id ?>"><?php echo $colaborador->nome ." ". $colaborador->sobrenome ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">&nbsp;</label>
                        <div class="controls">
                            <button type="submit" class="btn btn-info"><i class="icon-filter icon-white"></i>Filtrar</button>
                            <a class=" btn btn-inverse " href="javascript:self.print()"><i class="icon-print icon-white"></i>Imprimir</a>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="cabecalho-impressao" style="margin: auto;text-align: center;margin-top: -10px;width: 50%;display: none">
                <p>Período:
                    <b style="text-decoration: underline "><?php echo AppUtil::convertDateToString($this->data_inicial) ?></b>
                    a <b style="text-decoration: underline "><?php echo AppUtil::convertDateToString($this->data_final) ?></b>

            </div>
            <?php if ($this->funcionario != NULL) { ?>
                <div style="display: none" class="cabecalho-impressao">
                    <p><b>Colaborador: <?php echo $this->funcionario->getFullNome(). '.  Comissão Tipo: '. $this->funcionario->getComissaoTipo() . ' de '?></b>
                        <?php if ($this->funcionario->comissao_tipo == Usuario::PERCENTUAL){?>
                        <?php echo AppUtil::convertFloatToString($this->funcionario->comissao)?>%.
                   <?php } else {?>
                        R$<?php echo AppUtil::convertFloatToString($this->funcionario->comissao,'.')?>.
                    <?php }?>
                    </p>
                </div>
            <?php } ?>
            <hr/>
        </form>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Doc</th>
                <th>Data Pg</th>
                <th>Descrição</th>
                <th>Valor Pg</th>
                <th>Valor Recebido</th>
                <th style="text-align: right;">Comissão</th>
                <th style="text-align: right;">Saldo</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->list as $item): ?>
                <tr>
                    <?php if ($item->Procedimento->Usuario->comissao_tipo == Usuario::PERCENTUAL){?>
                    <?php $saldo = $saldo + ($item->pagamento_valor * ($item->Procedimento->Usuario->comissao /100)) ?>
                    <?php } else { ?>
                        <?php $saldo = $saldo + $item->Procedimento->Usuario->comissao?>
                    <?php }?>
                    <?php $total_entrada = $total_entrada + $item->vencimento_valor ?>
                    <?php $total_recebido = $total_recebido + $item->pagamento_valor ?>
                    <td><b><a target="_blank" href="<?php echo $this->baseUrl()?>/admin/lancamento/editar/id/<?php echo $item->id?>"><?php echo str_pad($item->id, 7, "0", STR_PAD_LEFT)?></a>
                        </b></td>
                    <td><?php echo AppUtil::convertDateToString($item->pagamento_data) ?></td>
                    <td style="text-transform: uppercase;"><?php echo AppUtil::resumeTexto($item->descricao,50) ?></td>
                    <td class="valores">R$ <?php echo AppUtil::convertFloatToString($item->vencimento_valor,'.') ?></td>
                    <td class="valores">R$ <?php echo AppUtil::convertFloatToString($item->pagamento_valor,'.') ?></td>
                    <?php if ($item->Procedimento->Usuario->comissao_tipo == Usuario::PERCENTUAL){?>
                    <td class="valores" style="color: black;text-align: right;font-weight: bold;">R$ <?php echo AppUtil::convertFloatToString($item->pagamento_valor * ($item->Procedimento->Usuario->comissao /100))?></td>
                    <?php } else { ?>
                        <td class="valores" style="color: black;text-align: right;font-weight: bold;">R$ <?php echo AppUtil::convertFloatToString($item->Procedimento->Usuario->comissao)?></td>
                    <?php }?>
                    <td class="valores" style="color: black;text-align: right;font-weight: bold;">R$ <?php echo AppUtil::convertFloatToString($saldo,'.') ?></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="7">&nbsp</td>
            </tr>
            <tr style="font-weight:bold">
                <td colspan="3">TOTAL</td>
                <td  style="color: blue;">( + ) R$ <?php echo AppUtil::convertFloatToString($total_entrada,'.') ?></td>
                <td  style="color: darkblue;">( + ) R$ <?php echo AppUtil::convertFloatToString($total_recebido,'.') ?></td>
                <td></td>
                <td  style="color: black;text-align: right ">( = ) R$ <?php echo AppUtil::convertFloatToString($saldo,'.') ?></td>
            </tr>
            </tbody>
        </table>
        <div style="float: right;display: none" class="cabecalho-impressao"> <p>Emitido dia: <?php echo date('d/m/Y H:i:s') ?></p></div>
    </div>
    <div class="cabecalho-impressao" style="display: none;margin: auto;width: 150px;height: 20px;margin-top: 20px">
        <img  style="height: 30px;width: 100px;opacity: 0.6;" src="<?php echo $this->baseUrl(); ?>/content/img/logo_holy.png">
    </div>
</div>
