<style>
    .label_dados{
        float: left;
        padding-left: 3px;
        padding-bottom: -20px;
    }
    .label_linha{
        border-bottom: 1px solid #000;
        float: left;
        padding-left: 3px;
        padding-bottom: -20px;
    }
    .label_dados p{
        font-size: 14px;
    }

    .table-bordered {
        border: 4px solid #dddddd;
        border-collapse: collapse;
        border-left: 4px solid #dddddd;
    }
    .forma_pagamento_tipo{
        text-transform: uppercase;
        background-color: #f5f5f5;
        font-weight:bold;
    }
</style>
<div style="width: 1000px;  margin:auto;padding: 5px;">

    <div style="margin: 10px">
        <div class="cabecalho-impressao" style="display: none">
            <img  style="float: left;height: 60px;margin-top: -10px;width: 90px;border: none;padding: 4px" src="<?php echo $this->baseUrl() ?>/content/img/logo-ela.png">
            <h5 style="text-align: center"><?php echo $this->empresa->nome_fantasia ?></h5>
            <p style="text-align: center;">CNPJ: <?php echo AppUtil::convertIntToCNPJ($this->empresa->cnpj) ?></p>
            <div style="margin: auto;width: 60%;margin-top: -10px">
                <p style="text-align: center"><?php echo $this->empresa->Endereco[0]->logradouro ?>, N°: <?php echo $this->empresa->Endereco[0]->numero ?> — <?php echo $this->empresa->Endereco[0]->bairro ?>, <?php echo $this->empresa->Endereco[0]->cidade ?> - <?php echo $this->empresa->Endereco[0]->estado ?></p>
            </div>
            <div style="margin: auto;width: 50%;">
                <h5 style="text-align: center;">Contas a Receber</h5>
            </div>
        </div>
        <form id="form_extrato" method="GET" action="" enctype="multipart/form-data">
            <fieldset>
                <?php echo $this->flashMessenger(); ?>
                <div class="noprint" style="margin: auto;width: 50%;">
                    <h3 style="text-align: center;">Contas a Receber</h3>
                </div>
            </fieldset>
        </form>
        <form id="form_extrato" method="GET" action="" enctype="multipart/form-data">
            <fieldset>
                <?php echo $this->flashMessenger(); ?>
                <div class="row well noprint">
                    <div class="span7">
                        <div class="control-group">
                            <label class="control-label" for="cliente">Cliente</label>
                            <div class="controls">
                                <select data-placeholder="[ Selecione o Cliente ]" class="input-xlarge chzn-select-deselect" name="cliente" id="cliente">
                                    <option value="0"></option>
                                    <?php foreach ($this->clientes as $cliente): ?>
                                        <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('cliente'), $cliente->id) ?> value="<?php echo $cliente->id ?>"><?php echo $cliente->getFullNome() ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="span2">
                        <div class="control-group">
                            <label class="control-label" for="forma_pagamento">Forma de Pagamento</label>
                            <div class="controls">
                                <select data-placeholder="[ Selecione a Forma de Pagamento ]" class="input-xlarge chzn-select-deselect" name="forma_pagamento" id="forma_pagamento">
                                    <option value="0"></option>
                                    <?php foreach ($this->forma_pagamentos as $forma_pagamento): ?>
                                        <option <?php echo ViewUtil::fillFieldSelect($this->repository_filter->getParamByField('forma_pagamento'), $forma_pagamento->id) ?> value="<?php echo $forma_pagamento->id ?>"><?php echo $forma_pagamento->descricao ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="span6">
                        <div class="control-group">
                            <label>&nbsp;</label>
                            <span class="control-label" for="data_inicial">Exibir lançamentos de</span>
                            <input class="txData input-small" id="data_inicial" name="data_inicial" type="text" value="<?php echo $this->repository_filter->getParamByField('data_inicial') ?>">

                            <span class="control-label" for="data_final">até</span>
                            <input class="txData input-small" id="data_final" name="data_final" type="text" value="<?php echo $this->repository_filter->getParamByField('data_final') ?>">
                        </div>
                    </div>
                    <div class="span2">
                        <div class="control-group">
                            <label>&nbsp;</label>
                            <div class="btn-concluir">
                                <button type="submit" class="btn btn-info">
                                    <i class="icon-filter icon-white"></i>Filtrar</button>
                            </div>
                        </div>
                    </div>
                    <div class="span3">
                        <div class="control-group">
                            <label>&nbsp;</label>
                            <a class=" btn btn-inverse " href="javascript:self.print()">
                                <i class="icon-print icon-white"></i>Imprimir</a>
                        </div>
                    </div>



                </div>
                <div class="noprint" style="margin: auto;width: 50%;">
                    <h3 style="text-align: center;">Contas a Receber</h3>
                </div>
            </fieldset>

            <div class="cabecalho-impressao" style="margin: auto;text-align: center;width: 50%;display: none">
                <p>Período:
                    <b style="text-decoration: underline "><?php echo AppUtil::convertDateToString($this->data_inicial) ?></b>
                    a <b style="text-decoration: underline "><?php echo AppUtil::convertDateToString($this->data_final) ?></b>
                </p>
                <p style="float: left">
                    <?php if ($this->repository_filter->getParamByField('forma_pagamento') != NULL) { ?>
                        Forma do Pagamento: <b style="text-decoration: underline "><?php echo AppUtil::convertDateToString($this->forma_pagamento) ?></b>
                    <?php } ?>
                </p>
                <p style="float: right">
                    <?php if ($this->repository_filter->getParamByField('situacao') != NULL) { ?>
                        Situação do Pagamento: <b style="text-decoration: underline "><?php echo AppUtil::convertDateToString($this->situacao_pagamento) ?></b>
                    <?php } ?>
                </p>
            </div>


        </form>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Data</th>
                <th>Cliente</th>
                <th>Descrição</th>
                <th>Valor</th>
            </tr>
            </thead>
            <tbody>
            <?php $total_valor = 0?>
            <?php foreach ($this->forma_pagamentos as $forma_pagamento): ?>
                <?php $count = 0 ; $valor =0?>
                <tr class="forma_pagamento_tipo">
                    <td colspan="3"><?php echo $forma_pagamento->descricao ?></td>
                    <td></td>
                </tr>
                <?php foreach ($this->list as $lancamento): ?>
                    <?php if($lancamento->pagamento_tipo_id == $forma_pagamento->id) { ?>
                        <tr>
                            <td><?php echo AppUtil::convertDateToString($lancamento->pagamento_data) ?></td>
                            <td style="text-transform: uppercase;"><?php echo $lancamento->Cliente->getFullNome() ?></td>
                            <td style="text-transform: uppercase;"><?php echo $lancamento->descricao ?></td>
                            <td class="valores"style="text-align: right;">R$ <?php echo AppUtil::convertFloatToString($lancamento->pagamento_valor, '.') ?></td>
                        </tr>

                    <?php $count++; $valor += $lancamento->pagamento_valor ; }?>
                <?php endforeach; ?>
                <tr class="forma_pagamento_tipo">
                    <td colspan="2">TOTAL</td>
                    <td style="text-transform: uppercase;"><?php echo $count?> Registros</td>
                    <td class="valores"style="text-align: right;">R$ <?php echo AppUtil::convertFloatToString($valor, '.') ?></td>
                </tr>
                <tr>
                    <td colspan="4"></td>
                </tr>
                <?php $total_valor += $valor?>
            <?php endforeach; ?>
            <tr style="font-weight:bold">
                <td colspan="3">TOTAL</td>
                <td  class="valores" style="text-align: right;">R$ <?php echo AppUtil::convertFloatToString($total_valor, '.') ?></td>
            </tr>
            </tbody>
        </table>
        <div style="float: right;display: none" class="cabecalho-impressao"> <p>Emitido dia: <?php echo date('d/m/Y H:i:s') ?></p></div>
    </div>
    <div class="cabecalho-impressao" style="display: none;margin: auto;width: 150px;height: 20px;margin-top: 20px">
        <img  style="height: 30px;width: 100px;opacity: 0.6;" src="<?php echo $this->baseUrl(); ?>/content/img/logo_holy.png">
    </div>
</div>
