<form id="form" method="POST" action="" enctype="multipart/form-data">
    <fieldset class=" well">
        <?php echo $this->flashMessenger(); ?>
        <div class="row">
            <div class="span8">
                <div class="control-group">
                    <label class="control-label" for="nome">Nome</label>
                    <div class="controls">
                        <input class="input-xxlarge" id="nome" name="nome" type="text" value="<?php echo $this->usuario_funcionalidade->nome ?>">
                    </div>
                </div>
            </div>

            <div class="span8">
                <div class="control-group">
                    <label class="control-label" for="modulo">Module</label>
                    <div class="controls">
                        <input class="input-xlarge" id="module" name="modulo" type="text" value="<?php echo $this->usuario_funcionalidade->module ?>">
                    </div>
                </div>
            </div>

            <div class="span8">
                <div class="control-group">
                    <label class="control-label" for="controlador">Controller</label>
                    <div class="controls">
                        <input class="input-xlarge" id="controlador" name="controlador" type="text" value="<?php echo $this->usuario_funcionalidade->controller ?>">
                    </div>
                </div>
            </div>

            <div class="span8">
                <div class="control-group">
                    <label class="control-label" for="acao">Action</label>
                    <div class="controls">
                        <input class="input-xlarge" id="acao" name="acao" type="text" value="<?php echo $this->usuario_funcionalidade->action ?>">
                    </div>
                </div>
            </div>

        </div>

    </fieldset>

    <hr/>
    <div style="width: 100%;height: 20px">
    <div class="btn-concluir">
        <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/admin/usuario-funcionalidade/">Cancelar</a>
        <button type="submit" class="btn btn-success btn-large">Salvar</button>
    </div>
    </div>
</form>