<div id="esquerda">

    <div style="margin: 10px">

        <a style="float: right;" class="btn btn-success btn-large" href="<?php echo $this->baseUrl(); ?>/admin/usuario-funcionalidade/novo/">
            <i class="icon-plus icon-white"></i> Novo </a>

        <button style="float: right; margin-right: 5px;"  type="button" id="btn_filtrar" class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtro</button>

        <div class="page-header" >
            <h2>Funcionalidades do Sistema</h2>
        </div>

        <form method="GET" action="" style="display: none;" id="form_filtrar">
            <div class="row well">
                <a id="btn_close" class="close" href="#">&times;</a>



                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="nome">Nome</label>
                        <div class="controls">
                            <input class="input-xlarge" id="nome" name="nome" type="text" value="<?php echo $this->repository_filter->getParamByField('nome') ?>">
                        </div>
                    </div>
                </div>
                <div class="span8">
                    <hr/>
                    <button type="submit" data-loading-text="Filtrando..." class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtrar</button>
                </div>

            </div>
        </form>

        <?php echo $this->flashMessenger(); ?>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><?php echo ViewUtil::getOrderBy('Nome', 'nome', $this->repository_order) ?></th>
                    <th>Module</th>
                    <th>Controller</th>
                    <th>Action</th>
                    <th colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->list as $item): ?>

                    <tr>
                        <td><?php echo $item->nome ?></td>
                        <td><?php echo $item->module ?></td>
                        <td><?php echo $item->controller ?></td>
                        <td><?php echo $item->action ?></td>
                        <td width="20px" style="text-align: center; vertical-align: middle;">
                            <a href="<?php echo $this->baseUrl(); ?>/admin/usuario-funcionalidade/editar/id/<?php echo $item->id; ?>"><i title="editar" class="icon-pencil"></i></a>
                        </td>
                        <td width="20px" style="text-align: center; vertical-align: middle;">
                            <a onclick="return confirm('Confirma a exclusão da funcionalidade ?')" href="<?php echo $this->baseUrl(); ?>/admin/usuario-funcionalidade/deletar/id/<?php echo $item->id; ?>"><i title="excluir" class="icon-trash"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <?php if (isset($this->list)) echo $this->paginationControl($this->list, "All", "paginator.phtml", $this->list_params); ?>

    </div>

</div>