<div id="esquerda">

    <div style="margin: 10px">



        <a style="float: right;" class="btn btn-success btn-large" href="<?php echo $this->baseUrl(); ?>/admin/usuario/novo/">
            <i class="icon-plus icon-white"></i> Novo </a>

        <button style="float: right; margin-right: 5px;"  type="button" id="btn_filtrar" class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtro</button>


        <div class="page-header" >
            <h2>Usuários</h2>
        </div>

        <form method="GET" action="" style="display: none;" id="form_filtrar">
            <div class="row well">
                <a id="btn_close" class="close" href="#">&times;</a>



                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="nome">Nome</label>
                        <div class="controls">
                            <input class="input-xlarge" id="nome" name="nome" type="text" value="<?php echo $this->repository_filter->getParamByField('nome') ?>">
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="control-group">
                        <label class="control-label" for="email">Email</label>
                        <div class="controls">
                            <input class="span4" id="email" name="email" type="text" value="<?php echo $this->repository_filter->getParamByField('email') ?>">
                        </div>
                    </div>
                </div>





                <div class="span8">
                    <hr/>
                    <button type="submit" data-loading-text="Filtrando..." class="btn btn-info btn-large"><i class="icon-filter icon-white"></i>&nbsp;Filtrar</button>
                </div>

            </div>
        </form>

        <?php echo $this->flashMessenger(); ?>
     
        <span class="help-block"><i class="icon-info-sign"></i> <i>Clique no email do usuário para reenviar o email de boas vindas com a autenticação do sistema.</i></span>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th><?php echo ViewUtil::getOrderBy('Nome', 'nome', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Sobrenome', 'sobrenome', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Email/Usuário', 'email', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Tipo', 'tipo', $this->repository_order) ?></th>
                    <th><?php echo ViewUtil::getOrderBy('Grupo', 'usuario_grupo_id', $this->repository_order) ?></th>                    
                    <th><?php echo ViewUtil::getOrderBy('Status', 'status', $this->repository_order) ?></th>                    
                    <th colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->list as $item): ?>

                    <tr>
                        <td><?php echo $item->nome ?></td>
                        <td><?php echo $item->sobrenome ?></td>
                        <td><a onclick="return confirm('Confirma o reenvio do email de boas vindas para <?php echo $item->nome ?> ?')" title="Reenviar email de boas vindas" href="<?php echo $this->baseUrl()?>/admin/usuario/reenviar/id/<?php echo $item->id; ?>"><?php echo $item->email ?></a></td>
                        <td><?php echo $item->getTipo() ?></td>
                        <td><?php echo $item->UsuarioGrupo->descricao ?></td>
                        <td><?php echo $item->getStatus() ?></td>
                        <td width="20px" style="text-align: center; vertical-align: middle;">
                            <a href="<?php echo $this->baseUrl(); ?>/admin/usuario/editar/id/<?php echo $item->id; ?>"><i title="editar" class="icon-pencil"></i></a>
                        </td>
                        <td width="20px" style="text-align: center; vertical-align: middle;">
                            <a onclick="return confirm('Confirma a exclusão do usuário ?')" href="<?php echo $this->baseUrl(); ?>/admin/usuario/deletar/id/<?php echo $item->id; ?>"><i title="excluir" class="icon-trash"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <?php if (isset($this->list)) echo $this->paginationControl($this->list, "All", "paginator.phtml", $this->list_params); ?>

    </div>

</div>