<script type="text/javascript">
    function removeImagemButton(id) {
        $('#remove').attr('value', id);
        $('#form_usuario').submit();
    }
</script>


<form id="form_usuario" method="POST" action="" enctype="multipart/form-data" autocomplete="off">
    <fieldset>
        <?php echo $this->flashMessenger(); ?>
        <div class="row well">
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="nome">Nome</label>
                    <div class="controls">
                        <input class="input-medium" autocomplete="off" id="nome" name="nome" type="text" value="<?php echo $this->usuario->nome ?>">
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="sobrenome">Sobrenome</label>
                    <div class="controls">
                        <input class="input-prepend" autocomplete="off" id="sobrenome" name="sobrenome" type="text" value="<?php echo $this->usuario->sobrenome ?>">
                    </div>
                </div>
            </div>
            <div class="span3" style="float: right">
                <div class="control-group">
                    <label class="control-label" for="imagem_perfil">Imagem do perfil</label>
                    <div class="controls">
                        <div class="row" >
                            <div id="result" style="background-color: #fff; margin: 10px 30px 10px 1px; padding: 5px;  float: left;" class="rounded-light shadow">
                                <img src="<?php echo AppUtil::getFileView($this->usuario, 'u', '160') ?>">
                            </div>
                            <div class="input-append">
                                <span class="btn success fileinput-button">
                                    <span>Selecionar imagem ...</span>
                                    <?php echo $this->form->file ?>
                                </span>
                                <?php if (AppUtil::isFileExists($this->usuario, 'u')) { ?>
                                    <a title="Remover imagem do perfil" class="btn" onClick="removeImagemButton(<?php echo $this->usuario->id ?>);">
                                        <i class="icon-trash"></i>
                                    </a>
                                    <input type="hidden" name="remove" id="remove">
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="cpf">CPF</label>
                    <div class="controls">
                        <input class="input-medium txCpf" autocomplete="off" id="cpf" name="cpf" type="text" value="<?php echo $this->usuario->cpf ?>">
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="control-group">
                    <label class="control-label" for="email">Email</label>
                    <div class="controls">
                        <input class="input-prepend" autocomplete="off" id="email" name="email" type="text" value="<?php echo $this->usuario->email ?>">
                    </div>
                </div>
            </div>

            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="usuario_grupo_id">Grupo</label>
                    <div class="controls">
                        <select  class="input-medium chzn-select-deselect" name="usuario_grupo_id" id="usuario_grupo_id">
                            <option value="0">[  Selecione o Grupo ]</option>
                            <?php foreach ($this->grupos as $grupo): ?>
                                <option <?php echo ViewUtil::fillFieldSelect($this->usuario->usuario_grupo_id, $grupo->id) ?> value="<?php echo $grupo->id ?>"><?php echo $grupo->descricao ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="control-group">
                    <label class="control-label" for="status">Status</label>
                    <div class="controls">
                        <select data-placeholder="[  Selecione o Status ]" class="input-prepend chzn-select-deselect" name="status" id="status">
                            <option <?php echo ViewUtil::fillFieldSelect($this->usuario->status, Usuario::ATIVO) ?> value="<?php echo Usuario::ATIVO ?>">Ativo</option>
                            <option <?php echo ViewUtil::fillFieldSelect($this->usuario->status, Usuario::INATIVO) ?> value="<?php echo Usuario::INATIVO ?>">Inativo</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="span3">
            <div class="control-group senha">
                <label class="control-label" for="senha">Senha</label>
                <div class="controls">
                    <input class="input-medium" autocomplete="off" id="senha" name="senha" type="text" value="<?php echo $this->usuario->senha ?>">
                </div>
            </div>
        </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="telefone_1">Celular 1</label>
                    <div class="controls">
                        <input class="input-large txCelular" autocomplete="off" id="telefone_1" name="telefone_1" type="text" value="<?php echo AppUtil::convertIntToCelular($this->usuario->Endereco[0]->telefone_1) ?>">
                    </div>
                </div>
            </div>
            <div class="span9">
                <div class="control-group">
                    <label class="control-label" for="telefone_2">Celular 2</label>
                    <div class="controls">
                        <input class="input-medium txCelular"  id="telefone_2" name="telefone_2" type="text" value="<?php echo AppUtil::convertIntToCelular($this->usuario->Endereco[0]->telefone_2) ?>">
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="tipo">Tipo</label>
                    <div class="controls">
                        <select data-placeholder="[  Selecione o Tipo ]" class="input-medium" name="tipo" id="tipo">
                            <option <?php echo ViewUtil::fillFieldSelect($this->usuario->tipo, Usuario::CILIOS) ?> value="<?php echo Usuario::CILIOS ?>">Cilios</option>
                            <option <?php echo ViewUtil::fillFieldSelect($this->usuario->tipo, Usuario::MASSAGEM) ?> value="<?php echo Usuario::MASSAGEM ?>">Massagem</option>
                            <option <?php echo ViewUtil::fillFieldSelect($this->usuario->tipo, Usuario::CILIOS_MASSAGEM) ?> value="<?php echo Usuario::CILIOS_MASSAGEM ?>">Cilios & Massagem</option>
                            <option <?php echo ViewUtil::fillFieldSelect($this->usuario->tipo, Usuario::ADMINISTRATIVO) ?> value="<?php echo Usuario::ADMINISTRATIVO ?>">Administrativo</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="span6">
                <div class="control-group senha">
                    <label class="control-label" for="cor">Cor</label>
                    <div class="controls">
                        <input class="input-medium" style="height: 35px" id="cor" name="cor" type="color" value="<?php echo $this->usuario->cor ?>">
                    </div>
                </div>
            </div>

            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="data_aniversario">Data de Aniversário</label>
                    <div class="controls">
                        <div class="input-append">
                            <input class="input-small txData"  autocomplete="off" id="data_aniversario" placeholder="__/__/____"name="data_aniversario" type="text"  value="<?php echo AppUtil::convertDateToString($this->usuario->data_aniversario) ?>">
                            <span class="add-on"><span class="icon-calendar"></span></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="admissao">Data de Admissão</label>
                    <div class="controls">
                        <div class="input-append">
                            <input class="input-small txData" autocomplete="off" id="admissao" placeholder="__/__/____"name="admissao" type="text"  value="<?php echo AppUtil::convertDateToString($this->usuario->admissao) ?>">
                            <span class="add-on"><span class="icon-calendar"></span></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="control-group">
                    <label class="control-label" for="demissao">Data de Demissão</label>
                    <div class="controls">
                        <div class="input-append">
                            <input class="input-small txData" autocomplete="off"  id="demissao" placeholder="__/__/____"name="demissao" type="text"  value="<?php echo AppUtil::convertDateToString($this->usuario->demissao) ?>">
                            <span class="add-on"><span class="icon-calendar"></span></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="comissao_tipo">Tipo de Comissão</label>
                    <div class="controls">
                        <select data-placeholder="[  Selecione o Tipo ]" class="input-medium chzn-select-deselect" name="comissao_tipo" id="comissao_tipo">
                            <option <?php echo ViewUtil::fillFieldSelect($this->usuario->comissao_tipo, Usuario::PERCENTUAL) ?> value="<?php echo Usuario::PERCENTUAL ?>">Percentual</option>
                            <option <?php echo ViewUtil::fillFieldSelect($this->usuario->comissao_tipo, Usuario::VALOR_FIXO) ?> value="<?php echo Usuario::VALOR_FIXO ?>">Valor Fixo</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="span2">
                <div class="control-group">
                    <label class="control-label" for="comissao">Comissão</label>
                    <div class="controls">
                        <input class="input-small txValor" autocomplete="off" id="comissao" name="comissao" type="text" value="<?php echo AppUtil::convertFloatToString($this->usuario->comissao) ?>">
                    </div>
                </div>
            </div>



        </div>


        <hr>
        <div class="row well">
            <div class="span4 ">
                <div class="control-group">
                    <label class="control-label" for="cep">CEP</label>
                    <div class="controls">
                        <input class="input-xlarge txCep endereco" autocomplete="off" placeholder="_____-___" id="cep" name="cep" type="text" value="<?php echo $this->usuario->Endereco[0]->cep ?>">
                        <img id="loading_cep" style="display: none;" src="<?php echo $this->baseUrl() ?>/content/img/loading.gif" />
                        <span id="erro_cep" style="display: none">Cep não encontrado</span>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="control-group">
                    <label class="control-label" for="logradouro">Endereço</label>
                    <div class="controls">
                        <input class="input-xlarge endereco" id="logradouro" name="logradouro" type="text" value="<?php echo $this->usuario->Endereco[0]->logradouro ?>">
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="numero">Nº</label>
                    <div class="controls">
                        <input class="input-small endereco" autocomplete="off" id="numero" name="numero" type="text" value="<?php echo $this->usuario->Endereco[0]->numero ?>">
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="control-group">
                    <label class="control-label" for="bairro">Bairro</label>
                    <div class="controls">
                        <input class="input-xlarge endereco" id="bairro" name="bairro" type="text" value="<?php echo $this->usuario->Endereco[0]->bairro ?>">
                    </div>
                </div>
            </div>

            <div class="span4">
                <div class="control-group">
                    <label class="control-label" for="cidade">Cidade</label>
                    <div class="controls">
                        <input class="input-xlarge endereco" id="cidade" name="cidade" type="text" value="<?php echo $this->usuario->Endereco[0]->cidade ?>">
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label" for="estado">UF</label>
                    <div class="controls">
                        <input class="input-small endereco" id="estado" maxlength="2"name="estado" type="text" value="<?php echo $this->usuario->Endereco[0]->estado ?>">
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="control-group">
                    <label class="control-label" for="complemento_endereco">Complemento Endereço</label>
                    <div class="controls">
                        <input class="input-xxlarge" autocomplete="off"  id="complemento_endereco" name="complemento_endereco" type="text" value="<?php echo $this->usuario->Endereco[0]->complemento_endereco ?>">
                    </div>
                </div>
            </div>
        </div>
    </fieldset>


    <hr/>
    <div style="width: 100%;height: 20px">
        <div class="btn-concluir">
            <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/admin/usuario/">Cancelar</a>
            <button type="submit" class="btn btn-success btn-large">Salvar</button>
        </div>
    </div>

</form>

<script src="<?php echo $this->baseUrl(); ?>/content/upload/jquery/js/load-image.min.js"></script>
<script type="text/javascript">
    var result = $('#result');

    document.getElementById('file').onchange = function(e) {
        window.loadImage(
            (e.dataTransfer || e.target).files[0],
            function(img) {
                result.children().replaceWith(img);
            },
            {
                maxWidth: 160,
                maxHeight: 160,
                canvas: true
            }
        );
    };


    function format_cep(cep) {
        cep = cep.replace(".", "");
        cep = cep.replace("-", "");
        cep = cep.replace(" ", "");
        cep = cep.replace(/_/g, "");
        return cep;
    }



    function format_string(str) {
        if (str == null)
            return '';
        str = str.replace(/-/g, " ");
        return str;
    }


    $("#cep").keyup(function(e) {

        var cep = format_cep($(this).val());
        if (cep.length < 8)
            return false;
        $('#data_fornecedor .endereco').attr('readonly', true);
        $('#erro_cep').hide();

        $.getJSON('<?php echo $this->baseUrl(); ?>/ajax/busca-cep/busca-cep', {cep: cep},
            function(endereco) {
                var data = jQuery.parseJSON(endereco);
                if (data.resultado == 1) {
                    $('#erro_cep').hide();
                    $("#logradouro").val(format_string(data.logradouro));
                    $("#numero").val('');
                    $("#bairro").val(format_string(data.bairro));
                    $("#cidade").val(format_string(data.cidade));
                    $("#estado").val(format_string(data.uf));
                    $("#numero").focus();
                    $('#loading_cep').hide();

                } else if (data.resultado == 0) {
                    $("#logradouro").val('');
                    $("#numero").val('');
                    $("#bairro").val('');
                    $("#cidade").val('');
                    $("#estado").val('');
                    $("#logradouro").focus();
                    $('#erro_cep').show('slow');
                }
                $('#data_fornecedor .endereco').attr('readonly', false);

            }, "json"
        );
    });
</script>
