<style>
    .body-content {
        border-radius: 10px;
        padding: 10px;
        margin: auto;
        width: 600px;
        border: 1px solid #ddd;
        margin-top: 40px !important;
        margin-bottom: 55px !important;
    }
    .content {
        margin: 10px;
        background: none repeat scroll 0 0 #f2f2f2;
        border: 1px solid #ddd;
        padding: 10px;
    }
    h1 {
        color: #0062A6;
        font-size: 18px;
        font-weight: bold;
    }

    .notice {
        background: url("<?php echo $this->baseUrl(); ?>/content/img/dialog-warning.png")  no-repeat scroll left top transparent;
        font-size: 14px;
        font-weight: bold;
        padding-left: 42px;
        padding-top: 13px;
    }
    h4{
        padding-top: 20px;
        font-size: 17px;
        margin-top: 17px;
    }
</style>
﻿<div id="esquerda" class="body-content">

    <div class="content">
        <h1>Lembrar senha <a target="_blank" href="<?php echo $this->baseUrl() ?>">SIGES</a></h1>
        <div style="float: right;background-color: #FFF;padding: 10px" class="shadow-light">
            <img height="70" src="http://siges.sbrasilsolucoes.com/content/img/logo_sbrasil.png">
        </div>

        <div class="notice" >Lembre-se de seu usuário e senha em instantes!</div>
        <h4>Esqueceu sua senha ? </h4>
        <p>Digite o endereço de e-mail que usou quando se cadastrou no <b><a target="_blank" href="<?php echo $this->baseUrl() ?>">SIGES</a></b>.
            <br> Em seguida, enviaremos um email com seu usuario e senha. </p>
        <form  method="POST" action="<?php echo $this->baseUrl() ?>/admin/conta/lembrarsenha" >
            <div style="padding: 5px; margin: 20px 0px; border-top: 1px solid #EEE;" >
                <label class="control-label" for="email"><b>Digite o seu e-mail cadastrado:</b></label>
                <input class="input-large" id="email" name="email" type="email" value="<?php echo $this->usuario->email ?>">
                <button id="btn_efetivar"  class="btn btn-info">Enviar</button> 
            </div>
            <div align="center" >
                <strong><?php echo $this->flashMessenger(); ?></strong>
            </div>
        </form>
    </div>

</div>

