<html><head ><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Lembrar Senha</title>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/content/css/site.css') ?>

        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/content/bootstrap/css/bootstrap.css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/content/bootstrap/js/jquery.js"></script>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/content/img/favicon.ico" type="image/ico" />


        <style>
            .body {
                height: auto;
                left: 50%;
                margin-top: 40px;
                margin-left: -400px;
                position: absolute;
                width: 800px;
                -webkit-box-shadow: 0 1px 0 rgba(0,0,0,.2),0 0 105px rgba(255,255,255,.35);
                -moz-box-shadow: 0 1px 0 rgba(0,0,0,.2),0 0 105px rgba(255,255,255,.35);
                box-shadow: 0 1px 0 rgba(0,0,0,.2),0 0 105px rgba(255,255,255,.35);
            }


            .body-content{
                background: none repeat scroll 0 0 #FFFFFF;
                border-radius: 10px 10px 10px 10px;
                font-family: Arial;
                padding: 10px;
            }
            .content {
                background: none repeat scroll 0 0 #dddcd9;
                border-radius: 5px 5px 5px 5px;
                font-size: 12px;
                line-height: 20px;
                padding: 10px;
            }
            h1 {
                color: #0062A6;
                font-size: 18px;
                font-weight: bold;
            }
            p {
                margin-bottom: 0;
                margin-top: 9px;
            }
            .details {
                float: left;
                width: 40%;
            }
            .details h3 {
                margin: 0;
            }
            .description {
                float: left;
                width: 60%;
            }
            .notice {
                background: url("<?php echo $this->baseUrl(); ?>/content/img/dialog-warning.png")  no-repeat scroll left top transparent;
                font-size: 14px;
                font-weight: bold;
                padding-left: 42px;
                padding-top: 9px;
            }
            h4{
                border-top: 1px solid rgb(204, 204, 204);
                padding-top: 20px;
                font-size: 17px;
                margin-top: 17px;
            }

        </style>


    </head >
    <body style="background-color: #000 !important; background: url(/content/img/bg-pattern.png);">
        <div class="body">
            <div class="body-content">
                <h1>Lembrar senha <a target="_blank" href="<?php echo $this->baseUrl()?>">Espaço ELA</a></h1>
                <div class="content" style="">
                    <div class="details">

                    </div>
                    <div style="float: right;background-color: #FFF" class="shadow-light">
                        <img height="150" src="http://www.sbrasilsolucoes.com/content/img/logo-cegetsemani.png">
                    </div>
                    <br clear="all">
                    <div class="notice" >Lembre-se de seu usuário e senha em instantes!</div>
                    <h4>Esqueceu sua senha ? </h4>
                    <p>Digite o endereço de e-mail que usou quando se cadastrou no <b><a target="_blank" href="<?php echo $this->baseUrl()?>">Espaço ELA</a></b>.
                        <br> Em seguida, enviaremos um email com seu usuario e senha. </p>
                    <form  method="POST" action="<?php echo $this->baseUrl() ?>/admin/conta/lembraraluno" >
                        <div style="padding: 5px; margin: 20px 0px; border-top: 1px solid #EEE;" >
                            <label class="control-label" for="email"><b>Digite a sua matrícula:</b></label>
                            <input class="input-large" id="matricula" name="matricula" type="text" value="<?php echo $this->usuario->matricula ?>">
                        </div>
                </div>
                <div align="center">
                    <strong><?php echo $this->flashMessenger(); ?></strong>
                    <button id="btn_efetivar"  class="btn btn-large btn-info">Enviar</button> 
                </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>