<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <meta charSet="utf-8"/>
    <meta name="description" content="🌟 Extensão de Cílios"/>
    <meta property="og:title" content="Espaço Lílian Assunção | Linktree"/>
    <meta property="og:description" content="🌟 Extensão de Cílios"/>
    <meta property="og:url" content="https://espacoela.com/link"/>
    <meta property="og:image" content="https://d1fdloi71mui9q.cloudfront.net/1woNeoB9QKugGZgWTOEZ_FXu6TsAAgbPB1cz8"/>
    <meta property="og:image:secure_url"
          content="https://d1fdloi71mui9q.cloudfront.net/1woNeoB9QKugGZgWTOEZ_FXu6TsAAgbPB1cz8"/>
    <meta property="og:updated_time" content="1615734323000"/>
    <meta property="profile:username" content="espacoela"/>
    <meta name="twitter:title" content="Espaço Lílian Assunção"/>
    <meta name="twitter:description" content="🌟 Extensão de Cílios e Massagens"/>
    <meta name="twitter:image" content="https://d1fdloi71mui9q.cloudfront.net/1woNeoB9QKugGZgWTOEZ_FXu6TsAAgbPB1cz8"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <link rel="canonical" href="espacoela.html"/>
    <script>window.__lter = window.__lter || {
            q: window.__lter && _lter.q || [], trackEvent: function () {
                __lter.q.push(Array.prototype.slice.call(arguments))
            }
        }</script>
    <script id="__ltcep" data-version="2" data-url="nktr.ee/uLZfGRmpj7il.ssergni//:sptth"
            src="https://assets.production.linktr.ee/cep/cep.min.js?v2"></script>
    <meta charSet="UTF-8"/>
    <meta content="ie=edge" http-equiv="x-ua-compatible"/>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"/>
    <meta property="og:image:height" content="600"/>
    <meta property="og:image:type" content="image/jpg"/>
    <meta property="og:image:width" content="600"/>
    <meta property="og:locale" content="en_US"/>
    <meta property="og:site_name" content="espacoela"/>
    <meta property="og:type" content="profile"/>
    <meta content="2419200"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:domain" content="Linktree"/>
    <meta name="theme-color" content="#ffffff"/>
    <meta content="d9fd170e8cf31c89537e" name="wot-verification"/>
    <meta content="211011856296014" property="fb:app_id"/>
    <script type="text/javascript" async="" src="https://www.googleadservices.com/pagead/conversion_async.js"
            nonce="3e886c473e92eda601a5200c599334a5"></script>
    <script type="application/ld+json">{
            "@context": "https://schema.org/",
            "@type": "WebPage",
            "name": "Espaço Lílian Assunção | Linktree",
            "url": "https://espacoela.com",
            "sameAs": [],
            "description": "🌟 Extensão de Cílios & Massagem",
            "image": "https://d1fdloi71mui9q.cloudfront.net/1woNeoB9QKugGZgWTOEZ_FXu6TsAAgbPB1cz8",
            "identifier": "espacoela",
            "alternateName": "@espacoela",
            "significantLink": "https://api.whatsapp.com/send?phone=+5531995114442&text=Olá,%20Gostaria%20de%20agendar%20com%20você!",
            "dateCreated": 1615569330000,
            "dateModified": 1615734323000,
            "isPartOf": "",
            "thumbnailUrl": "https://d1fdloi71mui9q.cloudfront.net/1woNeoB9QKugGZgWTOEZ_FXu6TsAAgbPB1cz8",
            "genre": "ecommerce",
            "keywords": "ecommerce, business-professional, fashion-beauty"
        }</script>
    <link rel="shortcut icon" href="static/favicon.ico"/>
    <link rel="icon" type="image/png" href="static/favicon.png"/>
    <link rel="icon" type="image/png" href="static/favicon-96x96.png" sizes="96x96"/>
    <link rel="icon" type="image/png" href="static/favicon-32x32.png" sizes="32x32"/>
    <link rel="icon" type="image/png" href="static/favicon-16x16.png" sizes="16x16"/>
    <link rel="apple-touch-icon" sizes="180x180" href="static/apple-icon-180x180.png"/>
    <link rel="apple-touch-icon" sizes="152x152" href="static/apple-icon-152x152.png"/>
    <link rel="apple-touch-icon" sizes="144x144" href="static/apple-icon-144x144.png"/>
    <link rel="apple-touch-icon" sizes="120x120" href="static/apple-icon-120x120.png"/>
    <link rel="apple-touch-icon" sizes="114x114" href="static/apple-icon-114x114.png"/>
    <link rel="apple-touch-icon" sizes="72x72" href="static/apple-icon-72x72.png"/>
    <link rel="apple-touch-icon" sizes="76x76" href="static/apple-icon-76x76.png"/>
    <link rel="apple-touch-icon" sizes="60x60" href="static/apple-icon-60x60.png"/>
    <link rel="apple-touch-icon" sizes="57x57" href="static/apple-icon-57x57.png"/>
    <meta name="msapplication-square310x310logo" content="static/ms-icon-310x310.png"/>
    <meta name="msapplication-square150x150logo" content="static/ms-icon-150x150.png"/>
    <meta name="msapplication-square70x70logo" content="static/ms-icon-70x70.png"/>
    <meta name="msapplication-TileImage" content="static/ms-icon-144x144.png"/>
    <meta name="msapplication-TileColor" content="#FFFFFF"/>
    <meta name="theme-color" content="#ffffff"/>
    <title>Espaço ELA</title>
    <meta name="next-head-count" content="9"/>
    <link rel="preload" href="https://assets.production.linktr.ee/profiles/_next/static/css/e143995825781cd87436.css"
          as="style" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://assets.production.linktr.ee/profiles/_next/static/css/e143995825781cd87436.css"
          crossorigin="anonymous" data-n-g=""/>
    <link rel="preload" href="https://assets.production.linktr.ee/profiles/_next/static/css/568bf93aa06827a714af.css"
          as="style" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://assets.production.linktr.ee/profiles/_next/static/css/568bf93aa06827a714af.css"
          crossorigin="anonymous" data-n-p=""/>
    <noscript data-n-css=""></noscript>
    <script defer="" crossorigin="anonymous" nomodule=""
            src="https://assets.production.linktr.ee/profiles/_next/static/chunks/polyfills-9ac4c4fcdeb1eb2c797a.js"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/webpack-4e43e8c24c4c995f311c.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/framework.dbcc724d78fa8404276a.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/commons.452eaffe218c55576591.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/e080fb28f6952cca57f97011e37be96262fed6b4.921d4f45c6f5b9be0cdb.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/main-11778dce35a6f3bcf4d5.js" defer=""
            crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/9e82d048.14ea90b1388410b512cc.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/777cf710.dd0aa37766e851483f8c.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/0f3c3701ba3bf6ec2f451d2e0b1bfae0a87f0f5c.60156af47d9bcf143f4b.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/b1542cc239bf56c8a14913c0a930efe682b5cf86.b9d1e0563c83c4e8ef38.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/pages/_app-eb579c489aa69e86e412.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/210f95f9.1b6decca13af91c320c8.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/29107295.308f77e7d25ce018476a.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/chunks/pages/%5Bprofile%5D-11e04c10dbac99e09f6e.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/6a744c0a531e22d9fa1323c16e041831fda43b1b/_buildManifest.js"
            defer="" crossorigin="anonymous"></script>
    <script src="https://assets.production.linktr.ee/profiles/_next/static/6a744c0a531e22d9fa1323c16e041831fda43b1b/_ssgManifest.js"
            defer="" crossorigin="anonymous"></script>
    <style data-styled="" data-styled-version="5.2.1">.fGhsIW {
            -webkit-flex-direction: column;
            -ms-flex-direction: column;
            flex-direction: column;
            position: relative;
            padding-bottom: 0;
            min-height: 100vh;
            overflow-x: hidden;
            width: 100%;
            height: 100%;
        }

        /*!sc*/
        .bcrzgk {
            -webkit-flex: 1;
            -ms-flex: 1;
            flex: 1;
            -webkit-flex-direction: column;
            -ms-flex-direction: column;
            flex-direction: column;
            -webkit-box-pack: justify;
            -webkit-justify-content: space-between;
            -ms-flex-pack: justify;
            justify-content: space-between;
            padding-left: 12px;
            padding-right: 12px;
            padding-top: 24px;
            padding-bottom: 24px;
            height: 100%;
            width: 100%;
        }

        /*!sc*/
        .LyLIy {
            margin: 0 auto;
            height: 100%;
            width: 100%;
            max-width: 680px;
            padding-bottom: 80px;
        }

        /*!sc*/
        .LQJMK {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            z-index: -1;
            background-position: center;
            background-size: cover;
            background-repeat: no-repeat;
            background-color: #d463a3;
            background-style: flat;
            background-gradient: linear-gradient(0deg, #fd8f67, #d463a3);
        }

        /*!sc*/
        .eZNKTD {
            margin-bottom: 16px;
        }

        /*!sc*/
        .jgGrsq {
            -webkit-align-items: center;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            -webkit-flex-direction: column;
            -ms-flex-direction: column;
            flex-direction: column;
            margin-top: 12px;
            margin-bottom: 32px;
            width: 100%;
            height: 100%;
        }

        /*!sc*/
        .llgrqs {
            margin-left: 12px;
            margin-right: 12px;
            max-width: 100%;
        }

        /*!sc*/
        .hTuoxC {
            padding-left: 40px;
            padding-right: 40px;
        }

        /*!sc*/
        .pkAuV {
            position: relative;
        }

        /*!sc*/
        .jxIDHS {
            position: relative;
            height: auto;
            style-type: outline;
            border-type: dotted;
        }

        /*!sc*/
        .fNlWAC {
            left: 4px;
            width: 46px;
            height: 46px;
            border-radius: 0;
        }

        /*!sc*/
        .ihnwqk {
            width: 100%;
            -webkit-box-pack: center;
            -webkit-justify-content: center;
            -ms-flex-pack: center;
            justify-content: center;
            height: 100%;
        }

        /*!sc*/
        .dkrNTA {
            position: fixed;
            bottom: 0;
            height: auto;
            margin: 0 auto;
            width: 100%;
            max-width: 375px;
            background-color: #ffffff;
            box-shadow: 0px -14px 28px rgba(10, 11, 13, 0.1);
            border-top-left-radius: 16px;
            border-top-right-radius: 16px;
            overflow: hidden;
            z-index: 1001;
        }

        /*!sc*/
        @media screen and (min-width: 576px) {
            .dkrNTA {
                max-width: 375px;
            }
        }

        /*!sc*/
        @media screen and (min-width: 767px) {
            .dkrNTA {
                max-width: 760px;
            }
        }

        /*!sc*/
        .bnzAjP {
            height: 0;
        }

        /*!sc*/
        .gchjEV {
            position: absolute;
            right: 8px;
            top: 8px;
        }

        /*!sc*/
        .eKvZIH {
            width: 100%;
            -webkit-flex-direction: column;
            -ms-flex-direction: column;
            flex-direction: column;
            max-height: 100vh;
            height: 100%;
        }

        /*!sc*/
        @media screen and (min-width: 576px) {
            .eKvZIH {
                -webkit-flex-direction: column;
                -ms-flex-direction: column;
                flex-direction: column;
            }
        }

        /*!sc*/
        @media screen and (min-width: 767px) {
            .eKvZIH {
                -webkit-flex-direction: row-reverse;
                -ms-flex-direction: row-reverse;
                flex-direction: row-reverse;
            }
        }

        /*!sc*/
        .kxNToM {
            width: 100%;
            -webkit-flex-basis: 80px;
            -ms-flex-preferred-size: 80px;
            flex-basis: 80px;
        }

        /*!sc*/
        @media screen and (min-width: 576px) {
            .kxNToM {
                width: 100%;
                -webkit-flex-basis: 80px;
                -ms-flex-preferred-size: 80px;
                flex-basis: 80px;
            }
        }

        /*!sc*/
        @media screen and (min-width: 767px) {
            .kxNToM {
                width: auto;
                -webkit-flex-basis: 30%;
                -ms-flex-preferred-size: 30%;
                flex-basis: 30%;
            }
        }

        /*!sc*/
        .hVYfjR {
            margin-bottom: 36px;
            padding-left: 32px;
            padding-right: 32px;
            padding-top: 36px;
            width: 100%;
            font-family: karla;
        }

        /*!sc*/
        @media screen and (min-width: 576px) {
            .hVYfjR {
                padding-top: 36px;
            }
        }

        /*!sc*/
        @media screen and (min-width: 767px) {
            .hVYfjR {
                padding-top: 40px;
            }
        }

        /*!sc*/
        .iOGite {
            margin-bottom: 24px;
        }

        /*!sc*/
        .fKOsqo {
            -webkit-align-items: center;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            -webkit-box-pack: center;
            -webkit-justify-content: center;
            -ms-flex-pack: center;
            justify-content: center;
            height: 0;
            min-height: 287px;
            max-height: 462px;
            width: 100%;
        }

        /*!sc*/
        @media screen and (min-width: 576px) {
            .fKOsqo {
                min-height: 287px;
                max-height: 462px;
            }
        }

        /*!sc*/
        @media screen and (min-width: 767px) {
            .fKOsqo {
                min-height: 287px;
                max-height: 462px;
            }
        }

        /*!sc*/
        @media screen and (min-width: 992px) {
            .fKOsqo {
                min-height: 270px;
                max-height: 425px;
            }
        }

        /*!sc*/
        .gNTMHV {
            height: 0vh;
        }

        /*!sc*/
        .VVPDD {
            width: 100%;
            -webkit-box-pack: center;
            -webkit-justify-content: center;
            -ms-flex-pack: center;
            justify-content: center;
            height: 100%;
            logo: black-green;
        }

        /*!sc*/
        .dxWfkp {
            height: 20px;
        }

        /*!sc*/
        data-styled.g1[id="sc-bdfBwQ"] {
            content: "fGhsIW,bcrzgk,LyLIy,LQJMK,eZNKTD,jgGrsq,llgrqs,hTuoxC,pkAuV,jxIDHS,fNlWAC,ihnwqk,dkrNTA,bnzAjP,jAmcnV,gchjEV,eKvZIH,kxNToM,hVYfjR,iOGite,fKOsqo,gNTMHV,VVPDD,dxWfkp,"
        }

        /*!sc*/
        .bhdLno {
            display: -webkit-box;
            display: -webkit-flex;
            display: -ms-flexbox;
            display: flex;
        }

        /*!sc*/
        data-styled.g2[id="sc-gsTCUz"] {
            content: "bhdLno,"
        }

        /*!sc*/
        .jHoJGf {
            margin: 0;
            color: #fff;
            font-weight: 700;
            font-size: 16px;
            line-height: 1.5;
            text-overflow: ellipsis;
            max-width: 100%;
            white-space: nowrap;
            overflow: hidden;
        }

        /*!sc*/
        .kwNybW {
            margin: 0;
            font-weight: 400;
            text-align: left;
            font-size: 24px;
            line-height: 1.5;
        }

        /*!sc*/
        @media screen and (min-width: 576px) {
            .kwNybW {
                text-align: left;
            }
        }

        /*!sc*/
        @media screen and (min-width: 767px) {
            .kwNybW {
                text-align: center;
            }
        }

        /*!sc*/
        data-styled.g3[id="sc-dlfnbm"] {
            content: "jHoJGf,kwNybW,"
        }

        /*!sc*/
        .fSnbkJ {
            padding: 0;
            margin: 0;
            text-align: center;
            line-height: 1.5;
            font-size: 14px;
            color: #fff;
        }

        /*!sc*/
        .kVCYxL {
            padding: 0;
            margin: 0;
            line-height: 1.5;
            width: 100%;
        }

        /*!sc*/
        .hyPPpq {
            padding: 0;
            margin: 0;
            color: #53585f;
            font-weight: 400;
            text-align: left;
            line-height: 1.5;
            font-size: 14px;
            line-height: 1.57;
        }

        /*!sc*/
        @media screen and (min-width: 576px) {
            .hyPPpq {
                text-align: left;
            }
        }

        /*!sc*/
        @media screen and (min-width: 767px) {
            .hyPPpq {
                text-align: center;
            }
        }

        /*!sc*/
        .cwiWLN {
            padding: 0;
            margin: 0;
            font-weight: 600;
            text-align: center;
            line-height: 1.5;
            font-size: 14px;
            line-height: 1.57;
        }

        /*!sc*/
        data-styled.g4[id="sc-hKgILt"] {
            content: "fSnbkJ,kVCYxL,hyPPpq,cwiWLN,"
        }

        /*!sc*/
        .kZodAG {
            color: inherit;
            -webkit-text-decoration: underline;
            text-decoration: underline;
        }

        /*!sc*/
        data-styled.g5[id="sc-eCssSg"] {
            content: "kZodAG,"
        }

        /*!sc*/
        .gAHPqj {
            fill: currentColor;
            display: block;
            width: lg;
            height: lg;
            color: black;
            width: 32px;
            height: 32px;
        }

        /*!sc*/
        .iSHMGE {
            fill: currentColor;
            width: xl;
            height: xl;
            color: #acb5bf;
            width: 48px;
            height: 48px;
        }

        /*!sc*/
        .eaSLVe {
            fill: currentColor;
            width: auto;
            height: 100%;
            display: block;
        }

        /*!sc*/
        data-styled.g7[id="sc-gKsewC"] {
            content: "gAHPqj,iSHMGE,eaSLVe,"
        }

        /*!sc*/
        .flTywP {
            width: 96px;
            height: 96px;
            border-radius: 50%;
            width: 96px;
            height: 96px;
            display: block;
            object-fit: contain;
            object-position: initial;
            -webkit-filter: none;
            filter: none;
        }

        /*!sc*/
        data-styled.g8[id="sc-iBPRYJ"] {
            content: "flTywP,"
        }

        /*!sc*/
        .irPtrP {
            -webkit-animation: spin 1s infinite linear;
            animation: spin 1s infinite linear;
        }

        /*!sc*/
        @-webkit-keyframes spin {
            from {
                -webkit-transform: rotate(0deg);
                -ms-transform: rotate(0deg);
                transform: rotate(0deg);
            }
            to {
                -webkit-transform: rotate(359deg);
                -ms-transform: rotate(359deg);
                transform: rotate(359deg);
            }
        }

        /*!sc*/
        @keyframes spin {
            from {
                -webkit-transform: rotate(0deg);
                -ms-transform: rotate(0deg);
                transform: rotate(0deg);
            }
            to {
                -webkit-transform: rotate(359deg);
                -ms-transform: rotate(359deg);
                transform: rotate(359deg);
            }
        }

        /*!sc*/
        data-styled.g9[id="sc-fubCfw"] {
            content: "irPtrP,"
        }

        /*!sc*/
        .ldGKnQ {
            padding: 0;
            margin: 0;
            border: none;
            font-family: inherit;
            font-weight: inherit;
            font-size: inherit;
            text-align: center;
            cursor: pointer;
            display: block;
            background: none;
            type: button;
            -webkit-text-decoration: none;
            text-decoration: none;
            display: -webkit-box;
            display: -webkit-flex;
            display: -ms-flexbox;
            display: flex;
            -webkit-align-items: center;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            -webkit-box-pack: center;
            -webkit-justify-content: center;
            -ms-flex-pack: center;
            justify-content: center;
            height: auto;
            position: relative;
            padding-top: 16px;
            padding-bottom: 16px;
            padding-left: 20px;
            padding-right: 20px;
            width: 100%;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            box-sizing: border-box;
            vertical-align: middle;
        }

        /*!sc*/
        .ldGKnQ:focus {
            outline: none;
        }

        /*!sc*/
        .ldGKnQ:disabled {
            cursor: default;
            pointer-events: none;
        }

        /*!sc*/
        data-styled.g10[id="sc-pFZIQ"] {
            content: "ldGKnQ,"
        }

        /*!sc*/
        html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, main, menu, nav, output, ruby, section, summary, time, mark, audio, video {
            margin: 0;
            padding: 0;
            border: 0;
            font-size: 100%;
            font: inherit;
            vertical-align: baseline;
        }

        /*!sc*/
        article, aside, details, figcaption, figure, footer, header, hgroup, main, menu, nav, section {
            display: block;
        }

        /*!sc*/
        *[hidden] {
            display: none;
        }

        /*!sc*/
        body {
            line-height: 1;
        }

        /*!sc*/
        ol, ul {
            list-style: none;
        }

        /*!sc*/
        blockquote, q {
            quotes: none;
        }

        /*!sc*/
        blockquote:before, blockquote:after, q:before, q:after {
            content: '';
            content: none;
        }

        /*!sc*/
        table {
            border-collapse: collapse;
            border-spacing: 0;
        }

        /*!sc*/
        html {
            font-family: Karla, sans-serif;
            font-size: 16px;
            font-weight: 700;
            box-sizing: border-box;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }

        /*!sc*/
        html > * {
            -webkit-letter-spacing: normal;
            -moz-letter-spacing: normal;
            -ms-letter-spacing: normal;
            letter-spacing: normal;
        }

        /*!sc*/
        *, *:before, *:after {
            box-sizing: inherit;
        }

        /*!sc*/
        data-styled.g16[id="sc-global-koxjWe1"] {
            content: "sc-global-koxjWe1,"
        }

        /*!sc*/
        .jvyDlw {
            display: grid;
            grid-template-columns:1fr auto 1fr;
            -webkit-align-items: center;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
        }

        /*!sc*/
        data-styled.g84[id="Header__Grid-sc-i98650-0"] {
            content: "jvyDlw,"
        }

        /*!sc*/
        .eiGOpF {
            grid-column-start: 2;
        }

        /*!sc*/
        data-styled.g85[id="Header__GridHeading-sc-i98650-1"] {
            content: "eiGOpF,"
        }

        /*!sc*/
        .dVjUsc {
            position: absolute;
            top: 50%;
            -webkit-transform: translateY(-50%);
            -ms-transform: translateY(-50%);
            transform: translateY(-50%);
            pointer-events: none;
            overflow: hidden;
            -webkit-box-pack: center;
            -webkit-justify-content: center;
            -ms-flex-pack: center;
            justify-content: center;
            -webkit-align-items: center;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            background-color: currentColor;
            -webkit-mask-image: url("https://assets.production.linktr.ee/69f882c0b4b5f731204a14612c2e8b1131422389/icons/tabler-icons/calendar-event.svg");
            mask-image: url("https://assets.production.linktr.ee/69f882c0b4b5f731204a14612c2e8b1131422389/icons/tabler-icons/calendar-event.svg");
            -webkit-mask-size: 100%;
            mask-size: 100%;
            width: 32px;
            height: 32px;
            left: 8px;
        }

        /*!sc*/
        .bjdPuW {
            position: absolute;
            top: 50%;
            -webkit-transform: translateY(-50%);
            -ms-transform: translateY(-50%);
            transform: translateY(-50%);
            pointer-events: none;
            overflow: hidden;
            -webkit-box-pack: center;
            -webkit-justify-content: center;
            -ms-flex-pack: center;
            justify-content: center;
            -webkit-align-items: center;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            background-color: currentColor;
            -webkit-mask-image: url("https://assets.production.linktr.ee/69f882c0b4b5f731204a14612c2e8b1131422389/icons/tabler-icons/book.svg");
            mask-image: url("https://assets.production.linktr.ee/69f882c0b4b5f731204a14612c2e8b1131422389/icons/tabler-icons/book.svg");
            -webkit-mask-size: 100%;
            mask-size: 100%;
            width: 32px;
            height: 32px;
            left: 8px;
        }

        /*!sc*/
        data-styled.g95[id="StyledThumbnail-sc-1hclpwd-0"] {
            content: "dVjUsc,bjdPuW,"
        }

        /*!sc*/
        .dhQIaC {
            overflow-wrap: break-word;
            word-wrap: break-word;
            word-break: break-word;
            -webkit-hyphens: auto;
            -moz-hyphens: auto;
            -ms-hyphens: auto;
            hyphens: auto;
            white-space: normal;
            background: none;
            color: inherit;
            -webkit-transition: box-shadow .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), border-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), -webkit-transform .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), background-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99);
            -webkit-transition: box-shadow .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), border-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), transform .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), background-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99);
            transition: box-shadow .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), border-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), transform .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), background-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99);
            padding-left: 66px;
            padding-right: 66px;
        }

        /*!sc*/
        data-styled.g96[id="StyledButton-sc-686c3k-0"] {
            content: "dhQIaC,"
        }

        /*!sc*/
        .bwrDfP {
            z-index: 0;
            overflow: hidden;
            margin-bottom: 16px;
            -webkit-transition: box-shadow .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), border-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), -webkit-transform .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), background-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99);
            -webkit-transition: box-shadow .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), border-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), transform .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), background-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99);
            transition: box-shadow .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), border-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), transform .25s cubic-bezier(0.08, 0.59, 0.29, 0.99), background-color .25s cubic-bezier(0.08, 0.59, 0.29, 0.99);
            border: 2px solid;
            border-color: #ffffff;
            background-color: transparent;
            color: #ffffff;
            border-radius: 0;
        }

        /*!sc*/
        @-webkit-keyframes topwave {
            from {
                -webkit-mask-position: 0 top;
                mask-position: 0 top;
            }
            to {
                -webkit-mask-position: 680px top;
                mask-position: 680px top;
            }
        }

        /*!sc*/
        @keyframes topwave {
            from {
                -webkit-mask-position: 0 top;
                mask-position: 0 top;
            }
            to {
                -webkit-mask-position: 680px top;
                mask-position: 680px top;
            }
        }

        /*!sc*/
        @-webkit-keyframes bottomwave {
            from {
                -webkit-mask-position: 0 top;
                mask-position: 0 top;
            }
            to {
                -webkit-mask-position: -680px top;
                mask-position: -680px top;
            }
        }

        /*!sc*/
        @keyframes bottomwave {
            from {
                -webkit-mask-position: 0 top;
                mask-position: 0 top;
            }
            to {
                -webkit-mask-position: -680px top;
                mask-position: -680px top;
            }
        }

        /*!sc*/
        .bwrDfP:hover {
            background-color: #ffffff;
            border-color: #ffffff;
            color: #d463a3;
        }

        /*!sc*/
        data-styled.g97[id="StyledContainer__StyledLinkContainer-sc-1kae6sc-0"] {
            content: "bwrDfP,"
        }

        /*!sc*/
        .rsIfq {
            position: relative;
            -webkit-hyphens: none;
            -moz-hyphens: none;
            -ms-hyphens: none;
            hyphens: none;
            -moz-hyphens: none;
            -ms-hyphens: none;
            -webkit-hyphens: none;
        }

        /*!sc*/
        data-styled.g110[id="Button__StyledText-sc-uh5tyw-0"] {
            content: "rsIfq,"
        }

        /*!sc*/
        .caAOvl {
            background: linear-gradient(0deg, #fd8f67, #d463a3);
            position: absolute;
        }

        /*!sc*/
        data-styled.g150[id="StyledProfileBackground-sc-1uifkkg-0"] {
            content: "caAOvl,"
        }

        /*!sc*/
        .bAHUYV {
            opacity: 0;
            -webkit-transition: opacity 500ms ease-in-out;
            transition: opacity 500ms ease-in-out;
        }

        /*!sc*/
        data-styled.g153[id="SignupBannerContainer__OpacityContainer-sc-1ialsxm-0"] {
            content: "bAHUYV,"
        }

        /*!sc*/
        .bbVlAa {
            height: 0px;
            -webkit-transition: height 500ms ease-in-out;
            transition: height 500ms ease-in-out;
        }

        /*!sc*/
        data-styled.g154[id="SignupBannerContainer__HeightContainer-sc-1ialsxm-1"] {
            content: "bbVlAa,"
        }

        /*!sc*/
        .hgkeGo {
            background-size: cover;
            background-position: center;
            background-image: url('https://assets.production.linktr.ee/profiles/_next/static/images/signup-banner-4f6a179612843b63eece3533261aa931.jpg'), linear-gradient(-40deg, transparent 0%, rgba(0, 0, 0, 0.2) 100%);
        }

        /*!sc*/
        data-styled.g155[id="SignupBannerOpen__Banner-sc-rdtv4q-0"] {
            content: "hgkeGo,"
        }

        /*!sc*/
        .bbAlHz {
            -webkit-transform: rotate(180deg);
            -ms-transform: rotate(180deg);
            transform: rotate(180deg);
            cursor: pointer;
            -webkit-transition: -webkit-transform 0.2s 0.2s ease-in-out;
            -webkit-transition: transform 0.2s 0.2s ease-in-out;
            transition: transform 0.2s 0.2s ease-in-out;
        }

        /*!sc*/
        data-styled.g156[id="SignupBannerToggle__Transition-sc-yw5ivp-0"] {
            content: "bbAlHz,"
        }

        /*!sc*/
        html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, main, menu, nav, output, ruby, section, summary, time, mark, audio, video {
            margin: 0;
            padding: 0;
            border: 0;
            font-size: 100%;
            font: inherit;
            vertical-align: baseline;
        }

        /*!sc*/
        article, aside, details, figcaption, figure, footer, header, hgroup, main, menu, nav, section {
            display: block;
        }

        /*!sc*/
        *[hidden] {
            display: none;
        }

        /*!sc*/
        body {
            line-height: 1;
        }

        /*!sc*/
        ol, ul {
            list-style: none;
        }

        /*!sc*/
        blockquote, q {
            quotes: none;
        }

        /*!sc*/
        blockquote:before, blockquote:after, q:before, q:after {
            content: '';
            content: none;
        }

        /*!sc*/
        table {
            border-collapse: collapse;
            border-spacing: 0;
        }

        /*!sc*/
        html {
            font-family: Karla, sans-serif;
            font-size: 16px;
            font-weight: 700;
            box-sizing: border-box;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }

        /*!sc*/
        html > * {
            -webkit-letter-spacing: normal;
            -moz-letter-spacing: normal;
            -ms-letter-spacing: normal;
            letter-spacing: normal;
        }

        /*!sc*/
        *, *:before, *:after {
            box-sizing: inherit;
        }

        /*!sc*/
        data-styled.g168[id="sc-global-koxjWe2"] {
            content: "sc-global-koxjWe2,"
        }

        .imagem {
            background-size: cover;
            background-position: center;
            background-image: url('<?php echo $this->baseUrl(); ?>/content/website/images/link.jpg');
        }

        /*!sc*/
    </style>
</head>
<body>
<div id="__next">
    <link href="https://fonts.googleapis.com/css2?family=Karla:wght@300;400;600;700&display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Karla:wght@300;400;600;700&display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet"/>
    <div class="imagem">
    <div class="sc-bdfBwQ sc-gsTCUz fGhsIW bhdLno"  >
        <div class="sc-bdfBwQ sc-gsTCUz bcrzgk bhdLno">
            <div class="sc-bdfBwQ LyLIy">
                <div class="sc-bdfBwQ StyledProfileBackground-sc-1uifkkg-0 LQJMK caAOvl"></div>
                <div class="sc-bdfBwQ eZNKTD">
                    <div class="sc-bdfBwQ sc-gsTCUz jgGrsq bhdLno">

                        <div class="sc-bdfBwQ Header__Grid-sc-i98650-0 llgrqs jvyDlw"><h1
                                    id="profile-espaco-lilian-assuncao"
                                    class="sc-dlfnbm Header__GridHeading-sc-i98650-1 jHoJGf eiGOpF"></h1></div>
                        <div class="sc-bdfBwQ hTuoxC"><h2 class="sc-hKgILt fSnbkJ"><br><br><br><br><br><br><br><br><br><br><br></h2></div>
                        <div class="sc-bdfBwQ hTuoxC"><h2 class="sc-hKgILt fSnbkJ"></h2></div>
                    </div>
                </div>
                <div id="69485616" class="sc-bdfBwQ pkAuV">
                    <div data-testid="StyledContainer"
                         class="sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 jxIDHS bwrDfP"><a
                                href="https://api.whatsapp.com/send?phone=+5531995114442&text=Ol%C3%A1%20gostaria%20de%20agendar%20meus%20c%C3%ADlios!"
                                target="_blank" rel="noopener" data-testid="LinkButton"
                                aria-describedby="profile-espaco-lilian-assuncao " height="auto"
                                class="sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dhQIaC">
                            <div data-testid="LinkThumbnail"
                                 class="sc-bdfBwQ sc-gsTCUz StyledThumbnail-sc-1hclpwd-0 fNlWAC bhdLno dVjUsc"></div>
                            <p class="sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq">CÍLIOS</p></a></div>
                </div>
                <div id="69485616" class="sc-bdfBwQ pkAuV">
                    <div data-testid="StyledContainer"
                         class="sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 jxIDHS bwrDfP"><a
                                href="https://api.whatsapp.com/send?phone=+5531995114442&text=Ol%C3%A1%20gostaria%20de%20agendar%20uma%20massagem."
                                target="_blank" rel="noopener" data-testid="LinkButton"
                                aria-describedby="profile-espaco-lilian-assuncao " height="auto"
                                class="sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dhQIaC">
                            <div data-testid="LinkThumbnail"
                                 class="sc-bdfBwQ sc-gsTCUz StyledThumbnail-sc-1hclpwd-0 fNlWAC bhdLno dVjUsc"></div>
                            <p class="sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq">MASSAGEM</p></a></div>
                </div>
                <div id="69486864" class="sc-bdfBwQ pkAuV">
                    <div data-testid="StyledContainer"
                         class="sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 jxIDHS bwrDfP"><a
                                href="https://espacoela.com" target="_blank" rel="noopener"
                                data-testid="LinkButton" aria-describedby="profile-espaco-lilian-assuncao "
                                height="auto" class="sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dhQIaC">
                            <div data-testid="LinkThumbnail"
                                 class="sc-bdfBwQ sc-gsTCUz StyledThumbnail-sc-1hclpwd-0 fNlWAC bhdLno bjdPuW"></div>
                            <p class=" Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq">WEBSITE</p></a></div>
                </div>
            </div>


        </div>
    </div>
</div>
</div>

</body>
</html>