<?php echo $this->flashMessenger(); ?>

<form id="form_fornecedor_categoria" method="POST" action="">
    <fieldset class="well">
        <div class="span5">
            <div class="control-group">
                <label class="control-label" for="descricao">Descrição</label>
                <div class="controls">
                    <input class="input-xlarge" id="descricao_categoria" name="descricao" type="text" value="<?php echo $this->fornecedor_categoria->descricao ?>">
                </div>
            </div>
        </div>
    </fieldset>

    <hr/>
    <div style="width: 100%;height: 20px">
        <div class="btn-concluir">
            <a class="btn btn-large" href="<?php echo $this->baseUrl(); ?>/admin/fornecedor-categoria/?nolayout=<?php echo $this->layout?>">Cancelar</a>
            <button type="submit" class="btn btn-success btn-large">Salvar</button>
        </div>
    </div>
</form>